### ISSUE TITLE
32 bit build?

### ISSUE THREAD

**Issue by zelon88** [iridium-browser/tracker#100]
Hello!

I have a dual core Intel Core Duo (the original) 32 bit processor as my portable dev machine. I remember when Google cared about us Linux folk I was able to install Chromium on this very machine. 

How would I go about building Iridium for my old-school 32-bit dev machine?

Thank you for your time!
-zelon88

**Comment by longsleep** [comment]
Well for now there are no Ubuntu 32-bit Linux builds - sorry!
