### ISSUE TITLE
Remove built-in extensions

### ISSUE THREAD

**Issue by Primokorn** [iridium-browser/tracker#102]
Hi,
How to remove Google Hangouts extension? I'm using the latest AUR (Arch Linux) snapshot.
Thanks.

**Comment by DebugReport** [comment]
Maybe set _enable_hangout_services_extension=false_?

**Comment by Primokorn** [comment]
Thanks but where do you find this option? I'm only used to play with Firefox about:config.

**Comment by DebugReport** [comment]
I found it here https://github.com/gcarq/inox-patchset

**Comment by Primokorn** [comment]
Well, I don't build myself...

**Comment by triceratops1** [comment]
@primokorn if you dont want build

use inox-bin (AUR)

**Comment by Primokorn** [comment]
@triceratops1 I finally switched back to chromium. Layout issues with some websites that don't support https. Many warning about insecure connections...
I'm ok with those warnings for new websites but it's annoying for websites that I visit daily.

**Comment by triceratops1** [comment]
@primokorn this is a new chromium feature, when arch updates chromium you gonna recieve it again
https://blog.chromium.org/2016/12/chrome-56-beta-not-secure-warning-web.html

PD i've uploaded an iridium binary iridium-bin 
its based at debian binary (just like google chrome)

**Comment by longsleep** [comment]
The AUR package is not official Iridium package. Please contact the creator of the package.
