### ISSUE TITLE
Missing PGP key from 44.1.0 up

### ISSUE THREAD

**Issue by szepeviktor** [iridium-browser/tracker#114]
https://downloads.iridiumbrowser.de/windows/46.0.0/
Please consider a release checklist/release script.

Thanks.

**Comment by bernhardreiter** [comment]
Hi, are you saying that an OpenPGP signature is missing from the windows release files? What would be the use case for you?

The download transfer itself seems to be secured by the TLS certificate. I haven't tried the .msi files, but they may be additionally signed. If they are not, they probably should be.
