### ISSUE TITLE
Rendering issues in 54.0 64 bit

### ISSUE THREAD

**Issue by schaloner** [iridium-browser/tracker#127]
Viewing [this site](https://deadbolt-scala.readme.io/) in Iridium results in an unusable page:

![readme-iridium](https://cloud.githubusercontent.com/assets/456058/22249503/88180286-e243-11e6-824d-861e9d4d6a26.png)

Checking it in Chrome results in a correctly rendered page:
![readme-chrome](https://cloud.githubusercontent.com/assets/456058/22249520/9ec669e6-e243-11e6-9664-305e8caf0780.png)

**Comment by longsleep** [comment]
This is most likely a certificate issue of some of the requests. There was a problem where Symatec certificates were involved with Iridium 54.0. Please check with 57.
