### ISSUE TITLE
NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED!

### ISSUE THREAD

**Issue by tonialb** [iridium-browser/tracker#128]
Hi guys,

When I try to go on AliExpress, I get the notification: **NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED**! Same issue on Amazon.com. To be sure, I tested with the latest Chrome version! Here everything is green! Weird! Same result (green padlock) with Palemoon, Cyberfox etc.

Any idea what causes this security issue? Btw, all tested are done on browsers without add-ons/extensions.

Thank you

![iridium vs chrome cert aliexpress](https://cloud.githubusercontent.com/assets/23280246/22554994/7de44484-e962-11e6-957c-d12ce5692436.png)
![iridium vs chrome cert amazon](https://cloud.githubusercontent.com/assets/23280246/22555008/8833268a-e962-11e6-8d9b-6004508a2729.png)

**Comment by souldanger** [comment]
Hi Toni
this is a known issue, see #124 .
we hope to have this fixed shortly.
Thanks!

**Comment by tonialb** [comment]
Hi souldanger,

Thanks for the clarification!

**Comment by souldanger** [comment]
#124

**Comment by medozas** [comment]
Builds have been fixed and uploaded - Thanks for reporting!
