### ISSUE TITLE
Remove nonfree bits of Chromium code

### ISSUE THREAD

**Issue by picsi** [iridium-browser/tracker#130]
According to https://libreplanet.org/wiki/List_of_software_that_does_not_respect_the_Free_System_Distribution_Guidelines#chromium-browser and https://bugs.chromium.org/p/chromium/issues/detail?id=28291 there are some nonfree bits of code in the browser, which should be removed.

**Comment by dotlambda** [comment]
Why not simply add a package for [iridiumbrowser.de](https://iridiumbrowser.de/)?

**Comment by dotlambda** [comment]
There is also [Inox](https://github.com/gcarq/inox-patchset) and [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium).

**Comment by longsleep** [comment]
Which non-free bits? Please clarify what you mean and why what should be removed.
