### ISSUE TITLE
Still access to google safebrowsing servers

### ISSUE THREAD

**Issue by scubasunny** [iridium-browser/tracker#131]
Even if some requests are send against cache.iridium.de still a lot of other requests are send against the original googles servers :

See part of squid log (logfile format combined)

::1 - - [01/Mar/2017:23:03:51 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 61926 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [01/Mar/2017:23:03:59 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 2494693 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [01/Mar/2017:23:19:00 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 42706 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [01/Mar/2017:23:19:06 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 2277143 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [01/Mar/2017:23:34:07 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 45239 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [01/Mar/2017:23:34:14 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 2039826 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
**## ::1 - - [01/Mar/2017:23:41:28 +0100] "CONNECT cache.iridiumbrowser.de:443 HTTP/1.1" 200 6086 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
**
::1 - - [01/Mar/2017:23:41:28 +0100] "CONNECT cache.iridiumbrowser.de:443 HTTP/1.1" 200 6086 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT**
::1 - - [01/Mar/2017:23:49:15 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 28452 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
**
::1 - - [01/Mar/2017:23:49:19 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 1477656 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:04:20 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 7618 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:04:23 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 1029863 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:19:24 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 4949 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:19:25 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 690110 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:34:26 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 1856 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:34:27 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 4420 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:41:28 +0100] "CONNECT cache.iridiumbrowser.de:443 HTTP/1.1" 200 6086 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:41:28 +0100] "CONNECT cache.iridiumbrowser.de:443 HTTP/1.1" 200 6086 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:49:28 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 6144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:00:49:28 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 8413 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:01:04:29 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 1399 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:01:04:30 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 2262 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:01:19:30 +0100] "CONNECT safebrowsing.google.com:443 HTTP/1.1" 200 1388 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT
::1 - - [02/Mar/2017:01:19:31 +0100] "CONNECT safebrowsing-cache.google.com:443 HTTP/1.1" 200 1389 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/54.0 Safari/537.36 Chrome/54.0.2840.71" TCP_TUNNEL:HIER_DIRECT

**Comment by spywatch** [comment]
Newer versions are still making google requests. Is anything going to be done about this? It's been over a year. I suggest either making Safe Browsing work completely avoiding google connections, or just disabling it by default.

**Comment by GoogleBot42** [comment]
Why advertise that privacy matters to this project when it clearly doesn't?  This issue has been open for a year without any signs of progress to the public.  #158 seems even worse, although, a bit harder to believe without verifying first.  For now, I will look elsewhere.  Please mention me if this changes.

**Comment by longsleep** [comment]
Please see our Wiki for details on Google safe browsing - https://github.com/iridium-browser/tracker/wiki/Differences-between-Iridium-and-Chromium#google-safe-browsing

The text there can be improved as the safe browsing database is synced from Google servers by direct requests after loading the catalog and index details from Iridium controlled cache. If you do not want this, you need to turn safe browsing off.
