### ISSUE TITLE
Google somehow it defines my ip

### ISSUE THREAD

**Issue by defenderdf** [iridium-browser/tracker#132]
Google somehow it defines my ip, although I'm sitting through tor with the WebRTC disabled. In SRWare with the same set of plug-ins determines the ip output node
https://ipv4.google.com/sorry/index?continue=https://translate.google.ru/
iridium 54.0

**Comment by longsleep** [comment]
I do not see how this is related to Iridium.

**Comment by gagabs** [comment]
If him is behind a proxy (Tor), how can Google determine his real IP?

**Comment by Osndok** [comment]
Surely he is used to the 'tor browser' than comes pre-configured, and just hasn't set his browser's "socks proxy" to send traffic through tor...

https://check.torproject.org/
https://tor.stackexchange.com/questions/3435/how-do-i-configure-chrome-to-use-tor

*Definitely* not an iridium problem, and not the "safe" or recommended tor setup anyway.

**Comment by longsleep** [comment]
Not relevant to Iridium.
