### ISSUE TITLE
NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED

### ISSUE THREAD

**Issue by hasi699** [iridium-browser/tracker#133]
With Iridium V54 32bit running under Windows 10 I get this HTTPS error on **all**  E-Banking URLs. 
You can try it on:  www.bankdirekt.at,  www.bawag.com,  [ebanking.easybank.at](url), [portal.hellobank.at](url), [online.bankaustria.at](url). 
All other browsers including Google Chrome, Vivaldi, Opera etc. don't get this error.

![screenshot](https://cloud.githubusercontent.com/assets/11783818/23805188/2b966c8a-05bd-11e7-822a-401ceb232ae4.png)

**Comment by hasi699** [comment]
I went back to Iridium Browser V 51.1 and the problem doesn't occur!

**Comment by medozas** [comment]
Hi, the build has been fixed and uploaded about 8 hours ago. Thanks for reporting!

**Comment by hasi699** [comment]
I'm very sorry but after redownloading the latest 32bit version 54 from https://downloads.iridiumbrowser.de/windows/  and reinstalling I get the same error as previously  NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED, e,g, from https://www.bankdirekt.at/. Did you really publish the fixed version?

**Comment by hasi699** [comment]
I have to apoligize, i wasn't aware that this issue is fixed by adding a command line argument to Iridium. the problem only reappeared after executing the browser directly from the .EXE file. When calling it from the link in the startmenu everything is OK.
