### ISSUE TITLE
UI language is wrong

### ISSUE THREAD

**Issue by api-walker** [iridium-browser/tracker#134]
I installed the Iridium Browser 54 on Ubuntu 16.10. The UI language is english, but I want german. How can I change that? Chromium or Chrome recognize that the systems default language is german and show german by default.

**Comment by longsleep** [comment]
Currently Ubuntu builds only include English only.

**Comment by medozas** [comment]
cleaning up - closing - outdated. thanks, please recheck with current 2017.10 / 61 release.
