### ISSUE TITLE
"E: Unable to locate package iridium-browser"

### ISSUE THREAD

**Issue by lbresinsky** [iridium-browser/tracker#135]
I added the repository for ubuntu as mentioned on the website, but i receive an `E: Unable to locate package iridium-browser` Error when running `sudo apt-get install iridium-browser `. When downloading the .deb file manually and trying to install via `sudo dpkg -i iridium-browser_current_amd64.deb`, I receive the following error message:

`dpkg: error processing archive iridium-browser_current_amd64.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 iridium-browser_current_amd64.deb`

I am running a kubuntu 16.04 i686 on a Intel(R) Core(TM) i3 CPU 540  @ 3.07GHz

**Comment by longsleep** [comment]
There are no 32-bit Ubuntu builds at the moment.
