### ISSUE TITLE
WebRTC site specific microphone/video settings not saved/not used

### ISSUE THREAD

**Issue by kaksikanaa** [iridium-browser/tracker#136]
Hello

We are using Iridium with Owncloud + Spreedme apps (+server). When user open the Spreedme apps and gives the site specific rights to access the mic and web cam, it works in Iridium on that session. But even the setting then goes to the permanent settings (on this site mic and video is always allowed) the Iridium still blocks these by default on the next session. Is there some other settings to be modified to get this working?

BR

**Comment by longsleep** [comment]
Iridium by default does not keep data persistent (even if the app requests it to). You can change this  in Iridium Settings in Privacy -> Content settings...

**Comment by kaksikanaa** [comment]
Ah, okay and thanks!
