### ISSUE TITLE
Incorrect icons on 32bit build!

### ISSUE THREAD

**Issue by tonialb** [iridium-browser/tracker#139]
Hi,

First of all thanks for the latest version of Iridium. Good job!

The issue: Iridium 32bit shows Chromium icons! While 64bit build is OK!

thanks

![iridium-dir](https://cloud.githubusercontent.com/assets/23280246/24838880/fbdf1b26-1d50-11e7-831b-e91061ac8eeb.png)

**Comment by medozas** [comment]
cleaning up - closing - outdated. thanks, please recheck with current 2017.10 / 61 release.
