### ISSUE TITLE
Iridium 64 bit Windows installer creates weird start-menu shorcuts

### ISSUE THREAD

**Issue by albertdev** [iridium-browser/tracker#143]
I've just installed Iridium 57.0 64-bit for Windows. This is a screenshot of the contents of Iridium's start menu folder:

![iridium-browser-shortcuts](https://cloud.githubusercontent.com/assets/1451362/25429982/21d509d0-2a7b-11e7-933f-0409c074b9ee.PNG)

I use an English Windows 10 (fully patched Anniversary edition) but the region is set to *Belgium* and the localization is set to *Dutch (Belgium)*. The installer was thus running in Dutch as well.

**Comment by medozas** [comment]
cleaning up - closing - outdated. thanks, please recheck with current 2017.10 / 61 release.
