### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by smaragdus** [iridium-browser/tracker#144]
Hello,

The so called "Portable Versions" (latest- "iridiumbrowser-58.0.0-x86.zip" and "iridiumbrowser-58.0.0-x64.zip") are not portable because they save "User Data" in AppData (C:\Users\User\AppData\Local\Iridium\User Data)- a truly portable version would not write outside its program folder. Iridium Portable should save "User Data" in the "Iridium" folder next to "iridium.exe", "Version folder" (current- 58.0.0.0), and "Dictionaries". Please have a look at Cent Browser (http://www.centbrowser.com/) which has implemented the portable version right,

**Comment by kirill2485** [comment]
Hello. Chromium already has this feature.

Please see https://www.chromium.org/user-experience/user-data-directory

So to do this, on the flash drive (or folder of where Iridium program file / folder is stored) create a new shortcut to Iridium.exe, and add the following argument to it: "--user-data-dir=IridiumUserData". This will create an "IridiumUserData" folder in the same directory where Iridium.exe is stored.

Double click the shortcut and boom - /IridiumUserData will be created.

Now you can (if you want to not accidentally create /Iridium on appdata) make Iridium.exe a hidden file (right click->properties->hidden), the shortcut file will remain the visible one.

**Comment by highend** [comment]
Where can I download the _portable_ version of your browser? You know, the one that doesn't write it's stuff into HKCU\Software\Iridium?

**Comment by highend** [comment]
Where can I download the _portable_ version of your browser? You know, the one that doesn't write it's stuff into HKCU\Software\Iridium?

Obviously, https://downloads.iridiumbrowser.de/windows/iridiumbrowser-latest-x86.zip
isn't the correct link...

**Comment by kirill2485** [comment]
@highend
As I said, all you have to do is add the --user-data-dir=/IridiumUserData tag to the shortcut and you should be good to go.

Replace the "dir" with the path where you want the portable version to save it's files to.

As for the register, you can make that register key read only and it should not overwrite the registery.

**Comment by highend** [comment]
@kirill2485 

I wasn't complaining about where the app is storing it's files / folders. As long as somebody can define a different folder (via, command line, an .ini file, whatever) I'm fine with it.

But an app that permanently stores keys / values in the registry without an option to change this behavior isn't at all portable...

**Comment by qeerl** [comment]
I agree with highend's comments. The description on the download page is misleading. Instead of "Portable" it should be entitled "Without installer".  Or a least include a readme explaining the command-line option, and telling the user that it will still store values in the registry.

**Comment by souldanger** [comment]
Hi guys 
thank you for your input - we have updated the website accordingly and added a note with the command-line option.

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
smaragdus and highend are right. I tried to set the folder to ".", to start it from a local and a virtual machine. When I did so, iridium says "Putting the folder on a net-devide causes crashes" (nearly). So iridium should use its folder like all other portables do by default.
From the virtual machine, iridium wasn't startable. This is not good. All arguments "you can set up here and there" are not the solution for this problem. Portable should be portable,

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
btw. If a developer read this. It would be nice, if two search-engins could be implemented, i.e.
iridium => google
iridium stealth => duckduckgo

**Comment by souldanger** [comment]
@TryingToFindALoginWhichIsNotRegistered default search engine is Qwant. The reason for this decision can be read in our faq [Iridium Browser - FAQ](https://iridiumbrowser.de/faq)
We will not add any Google services by default, but you are able to add any search engine or extension that you would like at your own discretion.

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
Hi Michael,

it was not my intension to use google or Qwand. I would find it nice  
to set a different searchengine for stealth-mode ([ctrl][shift][n]).

Thanks for the fast reaction
Martin



Zitat von Michael Suldinger <notifications@github.com>:

**Comment by ShalokShalom** [comment]
Qwant is owned by the most worst of all German newspapers and hardly connected to pharmacy and so on. Where are their servers? Which contracts are valid there? 

The only valid search engine I know is startpage. DDG is hosted on AMAZON IN THE USA.
