### ISSUE TITLE
Revoked TLS certificates shown as valid

### ISSUE THREAD

**Issue by anleko** [iridium-browser/tracker#151]
Iridium doesn't download CRLSets, and these are currently the only way Chromium deals with SSL/TLS certificate revocations. This results in non-expired revoked certificates being presented as valid in Iridium, e.g. on [https://revoked.grc.com/](https://revoked.grc.com/). Chrome (see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=362696)) and Firefox correctly show the certificate as revoked and invalid, while Iridium does not.

See attached screenshot for the current behavior on Iridium 58.0:
![2017-05-10-112601_1366x732_scrot](https://cloud.githubusercontent.com/assets/28593006/25893229/4d12b820-3577-11e7-8590-c06d46f170df.png)

**Comment by longsleep** [comment]
Well, certificates provided by CA's and their lists like revocations are basically useless and not robust. I personally think Iridium should never ever contact any CA's service what so ever.
