### ISSUE TITLE
public key error opensuse tumbleweed

### ISSUE THREAD

**Issue by IGUNUBLUE** [iridium-browser/tracker#152]
![captura de pantalla de 2017-06-02 09-05-30](https://cloud.githubusercontent.com/assets/934933/26729254/a6394f7e-4772-11e7-8f59-c22dbca749f4.png)
iridium-browser-58.0-1.12.x86_64.rpm:
    EncabezadoV3 DSA/SHA1 Signature, ID de clave ec07c591: NOKEY
    Resumen MD5:  OK (c19e0406014030abd5be61ef63e99aa8)
    V3 DSA/SHA1 Signature, ID de clave ec07c591: NOKEY

iridium-browser-58.0-1.12.x86_64 (iridium): Error de verificación de firma [4-La clave pública de firma no está disponible]
¿Abortar, reintentar o ignorar? [a/r/i] (a):

**Comment by longsleep** [comment]
@jengelh, @medozas can you take a look

**Comment by souldanger** [comment]
This issue has been solved in the current version 2017.11.
Please download from [https://iridiumbrowser.de/downloads/](https://iridiumbrowser.de/downloads/ "download Iridium Browser")
