### ISSUE TITLE
Feature request: iridium package at chocolatey.org

### ISSUE THREAD

**Issue by donestefan** [iridium-browser/tracker#153]
Hi,
since you already provide linux repos with iridium packages, would you mind maintaining an additional iridium package at chocolatey.org to keep windows users updated?
chocolatey.org provides a command line tool "choco" that is very much like "yum" - but for windows.
Software Packages will be hosted at chocolatey.org, but have to be maintained by the community or  (ideally) by the original software developer.

This would ease the pain of manualy checking and installing new iridium versions in windows.

**Comment by dimqua** [comment]
https://chocolatey.org/packages/iridium-browser/58.0.0

**Comment by donestefan** [comment]
Thanks a lot @dimqua !!!
I'm looking forward to see the package approved :)

**Comment by dimqua** [comment]
Approved.

**Comment by donestefan** [comment]
Great job 😃 
Thanks again!
