### ISSUE TITLE
Iridum does not tile in Awesome

### ISSUE THREAD

**Issue by GreeeneJD** [iridium-browser/tracker#154]
Iridim Version : 58.0
OS + version : Ubuntu Linux 16.04
CPU architecture (32-bit / 64-bit): 64 bit
window manager : Awesome 4.1 (https://awesomewm.org/)

I'm not sure but in version 54 it works

**Comment by longsleep** [comment]
Mhm this is strange. Can you check Chromium on your installation please?

**Comment by medozas** [comment]
cleaning up - closing - outdated. thanks, please recheck with current 2017.10 / 61 release.
