### ISSUE TITLE
wayland binaries version for ubuntu pls

### ISSUE THREAD

**Issue by likeubuntu** [iridium-browser/tracker#156]
hello. you can make binaries version iridium which use without root installation and xorg depends but use wayland protocol  for ubuntu? wayland is future and begin now.

thanks, your moove very nice and good look, respect.

**Comment by longsleep** [comment]
Well, the ubuntu packaging for chromium already has some wayland stuff - did you check how chromium handles wayland / how do you run chromium on ubuntu with wayland?

**Comment by likeubuntu** [comment]
@longsleep yes chromium have but not work. i run wayland without xwayland and now work only epiphany browser or web project gnome native wayland.  but chrome have fork ozone which work native with wayland but this project very long not supported. 

if iridium can make iridium with native wayland support is very good :)

**Comment by longsleep** [comment]
Iridium 2018.05 is built with wayland support - please open a specific ticket if it does not work for you.
