### ISSUE TITLE
Disable profile button

### ISSUE THREAD

**Issue by Wyse-** [iridium-browser/tracker#157]
I believe this has already been requested and implemented in the past (https://github.com/iridium-browser/tracker/issues/41), however the patch has been broken for a while now, the [profile button](https://i.imgur.com/KOrAXuG.png) is showing once again, and the `--disable-new-avatar-menu` flag is long gone. It would be awesome if this feature could somehow be reimplemented.

**Comment by Daedalon** [comment]
Being able to disable the profile button would be very convenient. One of the more popular reasons to use Iridium is the desire to avoid the profile or identity feature, which Chrome recently changed the behavior of. For all those who don't want to use this feature, the profile icon is clutter in the UI that opens the possibility to use it accidentally e.g. when someone else is using the browser.

**Comment by jengelh** [comment]
Fixed in version 2020.11.85.
