### ISSUE TITLE
Explanation about URLRequest logging everything

### ISSUE THREAD

**Issue by aventrax** [iridium-browser/tracker#158]
Hello,

  I'm using Iridium Browser for about one week. The advertising about transparency/privacy is almost everywhere on your main web site, so, when I saw *every HTTP request logged* on my syslog server, even in incognito mode, I were literally shocked.

Can you explain me this (using iridium stable for ubuntu):

/var/log/syslog

Jul  9 00:03:47 livingroom gnome-session[2625]: *** URLRequest(https://api.github.com/_private/browser/stats)
Jul  9 00:03:47 livingroom gnome-session[2625]: *** URLRequest(https://api.github.com/_private/browser/errors)
Jul  9 00:03:51 livingroom gnome-session[2625]: *** URLRequest(https://github.com/iridium-browser/tracker/issues/131?_pjax=%23js-repo-pjax-container)
Jul  9 00:03:52 livingroom gnome-session[2625]: *** URLRequest(https://avatars2.githubusercontent.com/u/26141896?v=3&s=52)
Jul  9 00:03:52 livingroom gnome-session[2625]: *** URLRequest(https://avatars0.githubusercontent.com/u/1667797?v=3&s=52)

Every request logged. I tried to remove the ~/.config/iridium folder, and cache, to be sure, but the logs are coming up instantly, filling my hard drive.

You should clarify this...

**Comment by medozas** [comment]
To be honest, no, not at all. there is nothing from the patchset phoning to github ... literally. nothing. please feel free to point out where in the sources ... https://dl.iridiumbrowser.de/source/

**Comment by citizen4** [comment]
Hi there,

I'm also experiencing this extensive logging behavior.
In my case it goes to STDOUT not syslog - so a &>/dev/null fixed it for me.
A strings'n'grep on the ubuntu binary revealed a suspicious format string: "%s*** %s(%s)%s"!
The fedora binary did not!

Just curious what this is all about! Some debug left over?

**Comment by longsleep** [comment]
Please check current version if it shows extensive debugging. If so, please open up a new ticket with details on the platform/ Iridium build and how to reproduce.
