### ISSUE TITLE
Unable to (temporarily) deactivate added extensions

### ISSUE THREAD

**Issue by mightythor40k** [iridium-browser/tracker#160]
I added some extensions, e.g. Adblock Plus. In some cases I want to deactivate it via the check button (at chrome://extensions/). The button is not greyed out, but still, I cannot uncheck it! The deinstall button (trash bin) does not work either. If I want to remove it completely I have to do it another way (e.g. via Details).

**Comment by souldanger** [comment]
Hi,
this is a bug on our end. we hope to have this fixed in a future version.
