### ISSUE TITLE
Create Fedora 26 repo

### ISSUE THREAD

**Issue by scottlinux** [iridium-browser/tracker#162]
Hi,

Thank you for this awesome project. Is it possible to create an updated Fedora 26 repo?

**Comment by medozas** [comment]
thanks for your report, we're on it to update our fedora/EL7 repos with the current release 2017.10/61.

**Comment by souldanger** [comment]
Hello there,
Fedora 26 is repo is set up - see [https://iridiumbrowser.de/downloads/fedora](https://iridiumbrowser.de/downloads/fedora)
