### ISSUE TITLE
WebRTC Leak

### ISSUE THREAD

**Issue by iffin2l** [iridium-browser/tracker#165]
I ran some webrtc leak tests here https://browserleaks.com and https://hidester.com/webrtc-ip-leak-test/ and unfortunately WebRTC both public and private ips are leaking
The only way I could prevent this leak was installing a chrome extension called ''WebRTC Leak Prevent''

I was wondering if you could add a No WebRTC build in your next update. There is already a noWebRTC Chromium build made by woolyss

**Comment by vomitous** [comment]
solved

https://torguard.net/blog/webrtc-leak-block-fix-released/

**Comment by medozas** [comment]
yes, the comment perfectly represents the problem. removing webrtc is not part of the roadmap of iridium.
