### ISSUE TITLE
Flash on Windows vs. Linux

### ISSUE THREAD

**Issue by Myrthian** [iridium-browser/tracker#167]
Just discovered iridium and I'm loving it.
Though one problem emerged: according to the comparison page of iridium vs. chromium flash is supposed to be disabled, but that isn't true.
On my Linux laptop(fedora 26) I have no flash using iridium compared to a chromium installation which has flash.
On my Windows PC I have working flash the moment I finished the installation.

How does that make any sense?

**Comment by medozas** [comment]
for installation on linux flash needs to be installed correctly, which possibly isn't and certainly is not by default in linux and is also not bundled with the distro per default. for installation of flash, please check how to install, by a fast search I've came across https://www.if-not-true-then-false.com/2010/install-adobe-flash-player-10-on-fedora-centos-red-hat-rhel/
