### ISSUE TITLE
Uninstalling an extension

### ISSUE THREAD

**Issue by kyle-sorensen** [iridium-browser/tracker#170]
If you go to chrome://extensions/ and attempt to remove an extension with the trash can icon, clicking the icon does nothing. 

You can still remove an extension by right clicking on the icon in the top right hand corner, but trashcan is broken at that url.

**Comment by alazare619** [comment]
Fresh Install confirming this bug.

**Comment by souldanger** [comment]
duplicate #146

**Comment by souldanger** [comment]
Hi guys
to uninstall extensions, click on the extension icon, right hand side of the adress bar. Then use dropdown menu to remove extension.
The options in chrome://extensions/ wont work as connected to Google's PlayStore and Iridium is blocking connections to Google,.
Thanks!
