### ISSUE TITLE
Unable to disable and update extensions; wrong source shown

### ISSUE THREAD

**Issue by SilenceIsG0lden** [iridium-browser/tracker#171]
All my extensions have not updated in quite a while (maybe never? I've only been using Iridium for a bit over a month). They also don't update when I enable developer mode and click on the update button. Nothing happens. I'm also unable to uncheck the "enabled" field (i.e., am unable to disable an extension) and ALL my extensions say "Not from Chrome Web Store." when I have just installed them from exactly there.

(I can check on and off the "allow in icognito," "collect errors" and "allow access to file URLs.")

**Comment by sapioit** [comment]
Was about to report the same problem.
Please fix this problem!

**Comment by SilenceIsG0lden** [comment]
sapioit - have you checked out the newest version yet to see if it's still a problem? I have ditched iridium in the meantime, couldn't deal with not getting updates. (am now using comodo dragon.)

**Comment by sapioit** [comment]
I'm on version 58 (latest available; up to date) and the problem still persists.
Heck, without a changelog I don't even know what's going on.
I remember I was on 57 but I updated hoping for a fix to this problem.

**Comment by SilenceIsG0lden** [comment]
My apologies. I had gotten a note saying there was an update to version 61 -- I just now realized that was for Ubuntu ONLY. Why they get an update from 60 to 61 and we're still on 58 on Windows, I have no clue. But you're right. I'm not fond of this use of github as the only way to get any kind of update. I was under the impression github was for developers only.

**Comment by sapioit** [comment]
Github IS for devs only. They're just lazy...

**Comment by fkr** [comment]
Indeed, this is a problem that seems to be existant across all platforms. Will look into this.

**Comment by souldanger** [comment]
duplicate #146

**Comment by souldanger** [comment]
Hi guys
to uninstall extensions, click on the extension icon, right hand side of the adress bar. Then use dropdown menu to remove extension.
The options in chrome://extensions/ wont work as connected to Google's PlayStore and Iridium is blocking connections to Google,.
Thanks!

**Comment by sapioit** [comment]
Well, you might want to make it work, somehow, since this is the first chromium fork I've seen with this problem, and I'm not the only one who will abandon Iridium for at least a few years, if it won't get fixed...

I mean, it might try to connect to Google, but isn't that to sync with the server? There should be a way to make it work even without connecting to Google.
