### ISSUE TITLE
early fifty nine

### ISSUE THREAD

**Issue by soupeater** [iridium-browser/tracker#172]
This adblocking enhancing extension, uBlock Protector Extension, requires 59

https://chrome.google.com/webstore/detail/ublock-protector-extensio/ggolfgbegefeeoocgjbmkembbncoadlb

😟  🏆 

Is 59 stored somewhere not obvious?  No, I have neither skills to compile any version of anything, nor the platform.

**Comment by vomitous** [comment]
+1

**Comment by fkr** [comment]
Thanks for reaching out. I've just test-installed this extension on a beta of the next release of iridium and it installs fine there.

**Comment by medozas** [comment]
ublock has been verified to be working with current 2017.10/61 release
