### ISSUE TITLE
Can`t set Iridium as default browser (Windows)

### ISSUE THREAD

**Issue by fireworkerfp** [iridium-browser/tracker#177]
It is not possible to set iridium as default browser. If i choose chromium as default (because iridium is not in the list) then nothing is gonna happen when i am clicking on links (from my messenger or emails). Normally the browser should start to open the link but with chromium (iridium) as default nothing happens. And everytime I start iridium by hand it suggest me to set it as my default browser.

Am I doing something wrong?

**Comment by souldanger** [comment]
Hi
on Win10, I do not encounter this problem...
Are you Running the latest build version 2017.10?

**Comment by fireworkerfp** [comment]
Hi,
thx for the reply. Under About iridium i have 2017.10.
Is there possible a newer 2017.10 build?
I am using Windows 10, too.

**Comment by souldanger** [comment]
Did you try to change it from Settings > Standard-Apps?

**Comment by fireworkerfp** [comment]
Yes I picked chroimum. I think this is the right one?

**Comment by souldanger** [comment]
Ohhhh!
it should say Iridium not Chromium...!?
<img width="188" alt="win10-iridium" src="https://user-images.githubusercontent.com/10036776/32282749-b9d73ee2-bf22-11e7-8793-7a1b085f2d1b.png">

**Comment by fireworkerfp** [comment]
I dont have Iridium to choose.

**Comment by souldanger** [comment]
thats odd...

**Comment by fireworkerfp** [comment]
I can choose: vivaldi, chrome, chromium, edge and firefox.
But I already remove vivaldi, chrome, chromium from my pc. Why are they shown in the list?
Thats confusing me.

**Comment by souldanger** [comment]
hmmmpf, seems like there is something wrong with your Windows... possibly the registry?

**Comment by fireworkerfp** [comment]
So i know cleaned the registry and remove iridium. Now i only have firefox and edge and ie to pick as default. I installed iridium again but it is not on the list and I can`t find it through windows search.

**Comment by souldanger** [comment]
let me see if any of our developers have an idea how to help you.
this may take some time...

**Comment by fireworkerfp** [comment]
ok thanks for your help!

**Comment by Alquimerico** [comment]
I've the exact same problem. Iridium doesn't appear in the list of avaliable web browsers when I try to chose a default.

**Comment by polarnyx** [comment]
same here, win10 and no iridium to choose as default. please dont let me live with edge as my default browser :(

**Comment by ajmgh** [comment]
I've just reinstalled Windows (buld 17023) and can replicate this, it just doesn't show in the Default apps list.

**Comment by ajmgh** [comment]
Looks like the URLAssociations refers to IridiumHTML which doesn't exist in the classes root.
You can workaround this by creating a structure in HKEY_CLASSES_ROOT that looks like this:
![](https://i.imgur.com/oN202bR.png)

**Comment by ole-tange** [comment]
I can confirm fireworkerfp's problem.

Browser: Version 2017.10 (Officiel version) (64-bit)
OS: Windows 10 pro

Given that ajmgh already has a workaround, I hope this can be incorporated in the next release.

**Comment by souldanger** [comment]
Dear All,
this issue has been solved in the current version **2017.11**.
Please download from [https://iridiumbrowser.de/downloads/](https://iridiumbrowser.de/downloads/ "download Iridium Browser")

**Comment by ole-tange** [comment]
I can confirm this issue has  been solved.

Thanks to everyone involved.
