### ISSUE TITLE
Inox patchset

### ISSUE THREAD

**Issue by dimqua** [iridium-browser/tracker#178]
How Iridium is compared to [Inox](https://github.com/gcarq/inox-patchset)? I mean, can you tell me please which impovements from Inox are missing in Iridium and visa versa?

**Comment by longsleep** [comment]
See https://github.com/iridium-browser/tracker/wiki/Differences-between-Iridium-and-Chromium for Iridium compared to Chromium. We have not conducted a comparison with Inox. Feel free to add your findings here or contribute to the Iridium wiki.
