### ISSUE TITLE
CTRL+mouse wheel does not zoom

### ISSUE THREAD

**Issue by ole-tange** [iridium-browser/tracker#181]
In Chromium (and many other programs) CTRL+mouse wheel changes zoom level.

I see no reason why Iridium should be any different.

**Comment by souldanger** [comment]
...and it zooms in and out like a charm in Windows, Ubuntu and openSUSE.
what platform are you using?

**Comment by ole-tange** [comment]
Go to http://iqcrypto.dk/
Use CTRL+MouseWheel

OS: Windows 10.

**Comment by souldanger** [comment]
well... you may want to contact the admin for the website to inform them about the problem.
But Iridium Browser does zoom any professional website - try it here, try it on iridiumbrowser.de or again any other decent website.
Thank you for your understanding.
