### ISSUE TITLE
browser crashes in Incognito mode on Windows

### ISSUE THREAD

**Issue by souldanger** [iridium-browser/tracker#184]
Iridium Browser crashes in Incognito mode on Windows.

Developers are looking into this.

**Comment by HairyMilkshakes** [comment]
Can report the same issue. Crash is on load attempt from both start menu and in browser menu.

**Comment by Xlebomnekormi** [comment]
Same here! Incognito window crashes browser on Win 8.1

**Comment by souldanger** [comment]
Hi All,
thanks a bunch for your input!
We will release a new build for Windows and macOS shortly that addresses the issue.
Please stand-by!

**Comment by souldanger** [comment]
update now available!
go and get it https://iridiumbrowser.de/downloads/
