### ISSUE TITLE
Cannot enable/disable/delete extensions from chrome://extensions/

### ISSUE THREAD

**Issue by working-name** [iridium-browser/tracker#187]
Hello there,

2017.10 64bit on macOS 10.12.6 has this bug where you cannot disable an extension or delete it once installed. I am aware of the "workaround" of right clicking the extension's button and removing it that way but that's hardly a disable and for those extensions without a button it's game over.

**Comment by souldanger** [comment]
duplicate #146

**Comment by Flashwalker** [comment]
And how can i delete extension that has no icon?

**Comment by working-name** [comment]
@Flashwalker if you can tell me which OS I can give you more specific instructions. 

Essentially there’s a manual way of removing extensions from any google based browser (Firefox is very similar too). You need to reach the folder Default in your user profile/Google/Chrome or in this case Iridium. Inside there there’s an extensions folder which contains all of them. All you need to do is match the extension ID in the extensions UI in the browser and delete the folder. Once you do, restart the browser and that extension is gone.

**Comment by Flashwalker** [comment]
I'm using Iridium and already tried this. It's a Muzli extension.
I removed the folder with the same name as id of that extension from "AppData\Local\Iridium\User Data\", but it's sill exists in browser.

And key in registry always restores:
[HKEY_USERS\S-1-5-21-264353458-2073425097-2392300849-1002\Software\Iridium\PreferenceMACs\Default\extensions.settings]
"glcipcfhmopcgidicgdociohdoicpdfc"="4FFF6E0337B4EC71FCE6E86FB0406497E0B7148922D57A94A0FBB3F863FF84D7"
