### ISSUE TITLE
Pre-compiled binary packages

### ISSUE THREAD

**Issue by zensubz** [iridium-browser/tracker#188]
Hi,

I use a different Linux (rpm-based distro) that is not listed in your Downloads section. In that case, all I do is grab a .deb package and convert it to .rpm using alien and then install it. While Iridium seems to run without any issues so far in my system, I wonder if it would be possible for you guys to release a pre-compiled binary package (in .tar.*z format) so that I grab it and install it the way it suits me. 

Thanks for developing Iridium.

**Comment by jengelh** [comment]
Distro packages are built with and for a particular distribution+version. The executables have load-time requirements on certain system libraries and ABIs thereof, which may or may not be in a prior or subsequent release of the distro, let alone in a different distribution altogether.
