### ISSUE TITLE
Switching users crashes Iridium

### ISSUE THREAD

**Issue by incIined** [iridium-browser/tracker#191]
When trying to add a new user or switch to Guest in Iridium, it'll open another Window for a split second before crashing. 

Version 2017.11 (Official Build) (64-bit)
Windows 10 Pro 1709

**Comment by souldanger** [comment]
Thanks so much for your input!
We will release a new build for Windows and macOS shortly that addresses the issue.
However, Iridium blocks connections to Google, therefore this button does not work. It should not be there at all... but ndevelopers haven't found a practicle way to remove it yet.

**Comment by souldanger** [comment]
this has been fixed!
please download updated version https://iridiumbrowser.de/downloads/
