### ISSUE TITLE
Unable to enable/disable extensions on version 62.1.0 !

### ISSUE THREAD

**Issue by ballios** [iridium-browser/tracker#192]
Why devs are still ignoring THESE PROBLEMS ?!
From version to version...

**1. It's unable to DELETE extensions too!**
**2. Unable to enable/disable extensions on version 62.1.0**

What did you do in the Chrome code?
Please fix all this issues at last!
👎

**Comment by souldanger** [comment]
duplicate #146

**Comment by Flashwalker** [comment]
And how can i delete extension that has no icon?
