### ISSUE TITLE
Android Iridium full port arm/x86 (with full UI)

### ISSUE THREAD

**Issue by D0ve** [iridium-browser/tracker#196]
I'm talking not about usual android version with native android ui, where code is different.

But , exactly the same code which using for iridium releases! Is it possible to port/compile it for Android arm/x86?
I hate poor android ui, and would glad using full usual iridium UI with Android!

BTW,  Android is very popular and popularity of iridium will be much increased !!!

**Comment by souldanger** [comment]
Iridium is all about privacy and it is really a completely different thing to keep data and traffic as private as possible on an Android or iOS device.
However, we would be more than happy if there is someone out there who would do a mobile version of Iridium, as we are a small team only.
