### ISSUE TITLE
Building from deb-src fails due to sed syntax error on Devuan ASCII

### ISSUE THREAD

**Issue by msiism** [iridium-browser/tracker#198]
I've tried building a .deb package from the deb-src package on Devuan ASCII today. The build process failed with the following error messages:
```
### configure
sed -e 's/@BUILD_DIST@/Devuan testing/unstable/g' \
    -e 's/@BUILD_DIST_NAME@/Devuan/g' \
    -e 's/@BUILD_DIST_VERSION@/testing/unstable/g' \
    -e 's/@UPSTREAM_VERSION@/2017.10/g' \
    debian/iridium-browser.sh.in > debian/iridium-browser.sh
sed: -e expression #1, char 31: unknown option to `s'
debian/rules:443: recipe for target 'debian/iridium-browser.sh' failed
make[1]: *** [debian/iridium-browser.sh] Error 1
make[1]: Leaving directory '/usr/local/src/iridium-browser-2017.10'
debian/rules:284: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```
The problem here seems to be that `Devuan testing/unstable` contains a slash. But the slash is already being used as a delimiter in the expression. If I understand `sed` right, changing 
```
sed -e 's/@BUILD_DIST@/Devuan testing/unstable/g' \
```
into something like

```
sed -e 's|@BUILD_DIST@|Devuan testing/unstable|g' \
```
should fix it (also in expression # 3).

**Comment by longsleep** [comment]
Mhm this would derive from upstream Chromium packaging and i would rather not change it. If you like please provide a pull request to https://github.com/iridium-browser/iridium-browser-ubuntu and i might reconsider.
