### ISSUE TITLE
KeePassXC-Browser don't work with Iridium Browser

### ISSUE THREAD

**Issue by diffusae** [iridium-browser/tracker#200]
After integration of KeePassXC-Browser nothing happens. No database is detected.
It doesn't ask for credentials. It only has encountered an error:
"Timeout or not connected to KeePassXC"

Maybe it happens only because of the extension or of the browser?

General Info
keepassxc-browser - Version 1.0.0

Operating system: Ubuntu 16.04.4 LTS
Browser: Iridium current version 2017.10

**Comment by diffusae** [comment]
After creating the directory ~/.config/iridium/NativeMessagingHosts and copying org.keepassxc.keepassxc_browser.json from Chromium it seems to work with Iridium, too.

keepassxreboot/keepassxc#1559

So it should be a issue with the extension.

**Comment by souldanger** [comment]
Thanks for letting us know!
