### ISSUE TITLE
Push to Chrome 63.0?

### ISSUE THREAD

**Issue by HairyMilkshakes** [iridium-browser/tracker#203]
Hi, a few of my extensions have started reporting incompatibility with Iridium as they require Chrome to be on 63.0. For example: https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb?hl=en

Any plans on pushing that through to the user soon?

**Comment by HairyMilkshakes** [comment]
No update?

**Comment by ncoleman** [comment]
I'm becoming more convinced the project is dead.  No updates for 5 months, devs not replying anywhere, etc.

**Comment by HairyMilkshakes** [comment]
Same - I am in the process of phasing out Iridium for something else. The plugins I use can't keep up with Iridium's lack of developments or security updates.

**Comment by souldanger** [comment]
Hi all,
apologies for the silence!
We are currently working on a new release based on Chromium v66.
This will hopefully be released within the next couple of weeks.
Thanks!

**Comment by longsleep** [comment]
We have 67 now.
