### ISSUE TITLE
Which Windows Version Should I Select?

### ISSUE THREAD

**Issue by calwest123** [iridium-browser/tracker#204]
I have windows 7 home edition...
Not sure about using the 32 or 64 bit version.
How can I find out which version to use?

**Comment by Lynnyx** [comment]
Go to control paner. Switch to Large icon view if it's not on that mode already. Click on System. You can see if your Windows is 32 or 64 bit at System type under the System heading.

**Comment by calwest123** [comment]
Yes, thank you for the information.
