### ISSUE TITLE
Chromecast not working

### ISSUE THREAD

**Issue by Lynnyx** [iridium-browser/tracker#205]
Casting to my chromecast isn't working with me. Is it just me? Is there even support built in on Iridium for casting?

**Comment by souldanger** [comment]
Chromecast, Amazon Video, Netflix, et cetera won't work with Iridium - they all rely on Google's Widevine extrension (or similar), collect user data and therefore is blocked by Iridium.

**Comment by souldanger** [comment]
Duplicate #169
