### ISSUE TITLE
[openSUSE_Leap_42.3] Problem: iridium-browser-2018.4.66.0-2.9.x86_64 requires libstdc++.so.6(GLIBCXX_3.4.23)(64bit), but this requirement cannot be provided

### ISSUE THREAD

**Issue by thomas-merz** [iridium-browser/tracker#206]
Hi folks,

I'm using this repository for openSUSE_Leap_42.3:
https://downloads.iridiumbrowser.de/openSUSE_Leap_42.3/

Updating Iridiumbrowser fails with the following error:

Problem: iridium-browser-2018.4.66.0-2.9.x86_64 requires libstdc++.so.6(GLIBCXX_3.4.23)(64bit), but this requirement cannot be provided
  uninstallable providers: libstdc++6-7.1.1+r248970-1.4.x86_64[repo-oss]
                   libstdc++6-7.2.1+r253435-3.2.x86_64[repo-update-oss]
                   libstdc++6-7.3.1+r258313-6.1.x86_64[repo-update-oss]
                   libstdc++6-7.3.1+r258812-10.1.x86_64[repo-update-oss]
 Solution 1: deinstallation of libstdc++6-gcc6-6.2.1+r239768-6.19.x86_64
 Solution 2: do not install iridium-browser-2018.4.66.0-2.9.x86_64
 Solution 3: break iridium-browser-2018.4.66.0-2.9.x86_64 by ignoring some of its dependencies

I have enabled all OpenSUSE 42.3 repos:
openSUSE-Leap-42.3-Non-Oss
openSUSE-Leap-42.3-Oss
openSUSE-Leap-42.3-Update-Non-Oss
openSUSE-Leap-42.3-Update-Oss

This problem seems to exist since 2018-04-18 05:05:05 - this is the last entry in my /var/log/zypp/history (I'm doing an update every early morning by cron). The last automatic update was this:
2018-01-16 07:23:19|install|iridium-browser|2017.11-1.5|x86_64

"zypper se -s iridium" shows:

S  | Name                        | Type       | Version         | Arch   | Repository
---+-----------------------------+------------+-----------------+--------+------------------
   | iridium-browser             | srcpackage | 2018.4.66.0-2.9 | noarch | iridium
i+ | iridium-browser             | package    | 2017.11-1.5     | x86_64 | (System Packages)
v  | iridium-browser             | package    | 2018.4.66.0-2.9 | x86_64 | iridium
   | iridium-browser-debuginfo   | package    | 2018.4.66.0-2.9 | x86_64 | iridium
   | iridium-browser-debugsource | package    | 2018.4.66.0-2.9 | x86_64 | iridium
i  | iridium-browser-ffmpegsumo  | package    | 54.0-2.1        | x86_64 | (System Packages)

Kind regards
Thomas

**Comment by longsleep** [comment]
@jengelh @medozas any idea?

**Comment by jengelh** [comment]
pick solution 1. libstdc++6-7.x is a higher version than libstdc++6-6.x anyway (they just can't coexist).
