### ISSUE TITLE
Unable to update Iridium on Debian squeeze (dependency issue).

### ISSUE THREAD

**Issue by tsjnachos117** [iridium-browser/tracker#210]
Hello, fellow human beings.

I'm trying to install the new version of Iridium (2018.5.67-1iridium1) on my Debian Stretch machine, and it says it needs libfontconfig1 >= 2.11.94. However, the newest version available in the repos is 2.11.0-6+b1. As a result, the package manager refuses to install the new version. Please remove the dependency for the newer version of libfontconfig1, and make a package that can use the older version.

PS: thank you for this wonderful browser.

**Comment by schaengel** [comment]
@tsjnachos117 It was because the build was based on ubuntu dependencies which required a different version. See related thread I have created https://github.com/iridium-browser/iridium-browser-ubuntu/issues/15

**Comment by longsleep** [comment]
I might switch build system for Ubuntu/Debian to Debian 9 if feasible.

**Comment by longsleep** [comment]
Closing as duplicate of https://github.com/iridium-browser/iridium-browser-ubuntu/issues/15 - Please continue discussion there.
