### ISSUE TITLE
security fails ??

### ISSUE THREAD

**Issue by Quetzaal** [iridium-browser/tracker#212]
what !! localhost is not available "offline" ?? and you want me to develop something being on-line ?

it's a nice idea to try to do something with the new google spyware, and try to desactive it... i do aggry with this goal

but/then where are the "developement offline options"

because i do supose that google "sniff all code" with the bug tracker, and with IA, only off-line mode is a few secure

**Comment by longsleep** [comment]
Closing since this is very unspecific. If you want to help with development of specific features of Iridium, feel free to subscribe to our mailing list and start discussion there.
