### ISSUE TITLE
Vimeo not working

### ISSUE THREAD

**Issue by juxi500** [iridium-browser/tracker#213]
Hello, when trying to play any video on Vimeo.com, vimeo player gives me this error: Unsupported viewing environment. Your system is having trouble playing this video. For more information, see our Help Center.

Please do you know what could be the problem?

**Comment by juxi500** [comment]
website https://www.youtube.com/html5 also states that h264 and mse & h264 codecs are unsupported in the browser

**Comment by medozas** [comment]
Thanks for reporting. The team is checking this and getting back to you. To help us, could you please state which platform you are using?

**Comment by juxi500** [comment]
Enterprise Linux 7.5

**Comment by longsleep** [comment]
Most likely rhel/fedora builds are without proprietary codecs which is in line with fedora policies and also the default for upstream chromium.

**Comment by medozas** [comment]
That is right. Thanks @longsleep, there is nothing we can do in this case without violating fedora policies and even importantly violating the MPEG LA license: http://www.mpegla.com/main/programs/AVC/Documents/avcweb.pdf

**Comment by juxi500** [comment]
Firefox for example uses ffmpeg which is currently installed on the system. Is something similar possible to do in Iridium Browser? (To make it use local codecs instead of (or together with) the codecs it is shipping with?)
