### ISSUE TITLE
No pages can load (not even internal chrome:// pages) in Windows XP, using Iridium versions 46, 47 or 48.2

### ISSUE THREAD

**Issue by JuzBeKind** [iridium-browser/tracker#216]
**Description of the issue:**
After entering a URL, the webpage display area just remains blank white; there is no apparent effort made to load the page. 

Occasionally the page loading indicator will be animated as if the browser is trying to load the page, but nothing is ever loaded and eventually a _Page Unresponsive_ prompt will appear. 
I found I can consistently trigger this occasional behavior by doing the following:  

1. Reopen the browser
2. Attempt to visit google.com (manually type the URL in the address bar)
3. Click the three-bars menu button
4. Click _Settings_

**Miscellaneous findings:**
- In Iridium 44.1 all pages load fine.
- In Iridium 46, 47 and 48.2 no pages can load, not even internal chrome:// pages.
- The issue is present whether using a virtual machine install of XP or an actual install of XP.
- The issue is present whether using the portable version, install version or 'extra' version of Iridium.
- Iridium 46, 47 and 48.2 load pages fine in Windows 7 (32-bit and 64-bit) on the same machine.
- Out of the 50+ browsers I've tested recently in XP, the only other browser that appeared to have the same issue was Epic Privacy Browser.

**Remarks:**
Let me know if you have any thoughts about what may be causing this issue.
I'll be happy to test any suggestions you may have.

Thank you

**OS:** 
Windows XP Professional SP3 32-bit (also tried in unofficial SP4 and the issue was still present)

**Comment by Necklaces** [comment]
Afaics, Iridium does not support XP:

> System requirements:
> • Windows 7+
> • An Intel Pentium 4 processor or later that's SSE2 capable

**Comment by souldanger** [comment]
Iridium does not support WindowsXP.
WindowsXP is highly insecure at this stage. Using a privacy enhanced browser will not change this in any way. We recommend not to use WindowsXP - especially when browsiung the internet.

**Comment by JuzBeKind** [comment]
I know an enormous amount about Windows XP and I don't share your opinion. 
And, like it or not, OS preference is still a thing and will continue to be.
Feel free to use the OS you want to use and I'll do the same.
We're not living in a technology dictatorship.
Thanks for letting me know you're not testing your browser in XP though. I'll find a way to get it working.
