### ISSUE TITLE
Unable to disable/enable or remove extensions

### ISSUE THREAD

**Issue by lozog** [iridium-browser/tracker#217]
When I try to do any of the above, I get the following error message in the console:
`Unchecked runtime.lastError while running management.setEnabled: Failed to find extension with id <id>`

Ubuntu 16.04.4
Version 2018.5 (Developer Build) Ubuntu 16.04 (64-bit)

**Comment by lozog** [comment]
I just read @146. In regards to souldanger's comment from Feb 9 - I am getting this behaviour for an unpacked extension I developed. I wouldn't think those are managed by the Play Store - perhaps there is more to this issue?

**Comment by souldanger** [comment]
apologies for the late reply!
Iridium does not block or disable extensions by default - please refer to chromium/chrome help about third party extensions.
