### ISSUE TITLE
Iridium icon malfunctions on Plank dock

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#219]
When the Iridium icon is pinned to [the Plank dock](https://code.launchpad.net/plank), the icon colour periodically suffers colour inversion, making it appear to flash (though this effect does not seem deliberate). I can attempt to provide screenshots if necessary.

Iridium 2018.5
Mint 19 (but issue observed on Mint 18 too)

**Comment by longsleep** [comment]
What is the Plank dock doing with the icon? Maybe the Linux icon can be improved - please provide a screenshot if possible animated webm or something like it which showcases the issue.

**Comment by CottonEaster** [comment]
Thanks. I have uploaded a webm video [here](https://app.box.com/s/2a6ujhu29euu11cceny2jrlrppln7hih).

**Comment by longsleep** [comment]
Interesting thanks :+1: - seem more like a bug in the dock to me though

**Comment by CottonEaster** [comment]
Well, (1) this is the only icon with which I've seen the problem, (2) if you can make more certain that it is a dock problem, and especially if you can get some understanding of the problem, then I'll report it to the Plank developers.

**Comment by CottonEaster** [comment]
I find that[ I have reported this to Iridium before](https://bugs.launchpad.net/plank/+bug/1724451), but the bug had no uptake.

**Comment by LinuxOnTheDesktop** [comment]
This problem still exists. Also, the comment above contains a mistake. For, the link is to a bug reported against **Plank**. But I do not know whether this icon problem is a problem with Iridium or a problem with plank or a problem with both.

**Comment by medozas** [comment]
Could not reproduce anymore. If you still seem to have this issue, please reopen!

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I find that I can reproduce this on one Mint computer and not on another. Both computers have the Iridium repository both are on version 2019.04 of Iridium (whereas my Windows computer is on version 2020.04 . .).

**Details of the Mint computer on which the Iridium icon _works properly_ on Plank**

OS: Linux Mint 19.3 Tricia x86_64
Host: 2325L19 ThinkPad X230
Kernel: 5.6.11-050611-generic
Resolution: 1366x768 @ 60.02Hz
DE: Cinnamon
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark (N_cinn)
Theme: Mint-Y-Dark [GTK2/3]
Icons: Paper [GTK2/3]
GPU: Intel 3rd Gen Core processor Graphics Controller
Plank version: 0.11.89 Release

**Details of the Mint computer on which the Iridium icon does _not_ work properly on Plank**

OS: Linux Mint 19.3 Tricia x86_64
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th
Kernel: 5.7.0-050700-generic
Resolution: 2560x1440 @ 60.01Hz
DE: Cinnamon
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark (N_cinn)
Theme: Mint-Y-Dark [GTK2/3]
Icons: Paper [GTK2/3]
GPU: Intel UHD Graphics 620
Plank version: 0.11.89 Release

The above makes visible differences between the two Mint machines that pertain to:

- kernel (but I've had the problem with various kernels);
- graphics hardware.
