### ISSUE TITLE
There are frequent certificate failures; these are incompatible with your raison d'etre

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#220]
A browser focused upon privacy and security, which, frequently, has a website that no browser can load because of certificate problems?

See also #218 on repository problems in Linux; I too am having and have had such problems.

I think you do not have enough people. Still, isn't certificate stuff something you can _automate_?

EDIT: the idea of Iridium is wonderful, but if these things keep happening people are going to stop using it.

**Comment by souldanger** [comment]
Thanks for letting us know!
We have had some server issues which resulted in certificates not getting renewed as planned.
Please accept our apologies.
