### ISSUE TITLE
Javacript implementation problem

### ISSUE THREAD

**Issue by DrDonkey** [iridium-browser/tracker#223]
![2018-09-09-060307_1366x768_scrot](https://user-images.githubusercontent.com/18498932/45259870-fc3d4280-b3f6-11e8-9e07-ecca04ef259c.png)
Do I have to explain about it?
When I choose var name similar to first one then the result is as above.
Like if I choose first var as _inputName_ and 2nd var as _name_ then result is as above,
But if I choose first var as _inputName_ and 2nd var as _hehe_ then works fine.

**Comment by longsleep** [comment]
Not getting it, anyways please try with newer Iridium version and reopen if still a problem.
