### ISSUE TITLE
Is Iridium dead?

### ISSUE THREAD

**Issue by dimqua** [iridium-browser/tracker#225]
The latest commit in repository was 2018-05-17.

**Comment by RaiKoHoff** [comment]
Meanwhile, the basement Chromium/Chrome got a lot of security fixes, see:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security
https://chromereleases.googleblog.com/search/label/Stable%20updates

Iridium's claim: 
> "the latest and best secure technologies are used"

is not valid anymore.
So latest Iridium version, despite of protecting your privacy better than other browsers, can not be seen as a _"secure browser"_ any longer.

**Comment by Fafoulous** [comment]
I'm beginning to believe it ... no version 2018.5 for windows, too bad

**Comment by ktleary** [comment]
Finally uninstalled after numerous cert / ppa warnings from ubuntu -- too bad.

**Comment by souldanger** [comment]
@ktleary what Ubuntu version are you using?
We have just release a new build for Ubuntu 16.04+

**Comment by dylmye** [comment]
Sorry to bump an old thread but it appears so. OP hasn't asked for maintainers...
