### ISSUE TITLE
Addon issue

### ISSUE THREAD

**Issue by iezzimatica** [iridium-browser/tracker#228]
Hi Folks,
I`ve ran into a problem with the very latest x64 issue for Windows (10 Pro).
I installed the Internet Download Manager addon from a decompressed addon coming from another Chromium based browser, then I added the crx one manually (not the one coming from IDM itself).
Iridium recognised two different addons under the same name.
I tried to remove the first one by all the means, including uninstalling the browser and making a registry cleaning via:
MyCleanPc
CCleaner Pro
Glary Utilities Pro
Advanced Uninstaller Pro

I've then reinstalled Iridium but the issue is still there.
How shall I get rid of?
I'm out of options!

![whatsapp image 2018-12-17 at 22 46 35](https://user-images.githubusercontent.com/833942/50127281-5009c400-024f-11e9-86d1-f70bac28eed9.jpeg)

Another question: why web.whatsapp.com asks for a Chrome 36+ release to works and doesnt open in Iridium based on Chromium 71?
It´s quite strange. Any problems in reading the user agent maybe?
Waiting for some workaround for the addon issue I remain.
Tx in advance n rgds.

John

**Comment by souldanger** [comment]
Hi John
it looks like the problem is the extension you installed and not Iridium.
Please refer to 'How to uninstall Chrome extensions manually'.
Same goes with WhatsApp unfortunately - it's the app who is asking for Chrome/Firefox not us blocking the service.
Best
