### ISSUE TITLE
iridium additional sources does not work in LinuxMint 18.3 and 19.1

### ISSUE THREAD

**Issue by svgt** [iridium-browser/tracker#229]
hello,

when I update my LinuxMint systems, I get an error message  concerning Iridium.
das depot "https://downloads.iridiumbrowser.de/deb stable Release" enthält keine Release-Datei mehr.

any mistake from me? habe ich was falsch gemacht?

gruß svgt

**Comment by longsleep** [comment]
Mhm that should work, please reopen if it still does not, including details and terminal output.
