### ISSUE TITLE
Where'd my logins go?

### ISSUE THREAD

**Issue by bikrgran** [iridium-browser/tracker#232]
I've been using Iridium for some time, now, but all of a sudden I can't log into some of my sites (Amazon & Goodreads).  I have to use Firefox for that.  They worked until just a few weeks ago.  What's happened?

**Comment by souldanger** [comment]
Hi 
we did not do any changes or updates recently and we also haven't added anything to prevent loggin in to any sites....
Is it possible that you added some extension or add-on that creates any problems?
What does your console say?

**Comment by bikrgran** [comment]
Thanks for the reply.  I'm good.  I upgraded my Linux Mint to 19.0 and
several problems that had shown up, are gone, so I don't know what the deal
was.
