### ISSUE TITLE
Cannot Use WhatsApp Web Anymore

### ISSUE THREAD

**Issue by ohare93** [iridium-browser/tracker#233]
I could use [WhatsApp web](https://web.whatsapp.com/) in a previous version of Iridium (maybe from 6months ago), yet when I updated a month or so ago I now cannot access it. No clearing of cookies or reinstalls help. It still works on Chrome, Firefox, and Edge on my computer.

![image](https://user-images.githubusercontent.com/1471350/52648215-0b607900-2ede-11e9-90d5-c4f9c6fcb31a.png)

**Comment by Flaflo** [comment]
Same problem for me! This might be caused by an outdated chromium version iridium is built on.

**Comment by longsleep** [comment]
Please send your complaints to WhatsApp since they seem to use a sort of browser detection.

Maybe its based on request headers but since WhatsApp is proprietary its impossible to tell what exactly. You can try to experiment with extensions which modify the user agent header.

Iridium currently sends this:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/2019.04 Iridium/2019.04 Safari/537.36 Chrome/73.0.0.0
```

**Comment by Flaflo** [comment]
Why complaining whatsapp if it is Iridium that is not built in thr newest chromium?

Ive used a chromium headless on newest Version which opens whatsapp web just fine.

(Nicht gerade die feine englische Art zu sagen "Die sind Schuld beschwert euch bei dem und dem" wenn doch ganz klar Iridium hier der nicht funktionierende Part ist. mMn)

So oft course I dont know if eventually WhatsApp just has some other verification stuff going arround which the Iridium Browser is blocking with its security features

**Comment by longsleep** [comment]
It's not Iridium and if you look carefully then you will notice that latest iridium is built with chromium 73 which is pretty recent. If you have more details why WhatsApp is not detecting chromium properly please share - but it's not related to the version of iridium.

**Comment by longsleep** [comment]
Quick search resulted in https://askubuntu.com/questions/1100645/whatsapp-web-is-asking-to-update-chrome-while-using-chromium

So please complain to WhatsApp to fix their stuff or use an user agent switcher extension to send whatever they accept.
