### ISSUE TITLE
Unable to install Iridium on Devuan 2.0.0 ASCII

### ISSUE THREAD

**Issue by qupere** [iridium-browser/tracker#234]
I've just installed Devuan ASCII in a virtual box and tried installing Iridium Browser, exactly
according to the instructions. But I was unable to fetch anything from the repository while attempting to update and I just couldn't install the program.

![virtualbox_devuan vm_27_02_2019_18_26_38](https://user-images.githubusercontent.com/48066736/53513487-3e4d6400-3abd-11e9-9c84-7a179f86689d.png)

**Comment by longsleep** [comment]
Not sure what the problem is here - https://downloads.iridiumbrowser.de/deb/dists/stable/InRelease is a file which exists. Why it fails to fetch for you seems to be outside of Iridium browser. Please reopen if you think this is an issue of our repository and if so please explain.
