### ISSUE TITLE
https://iridiumbrowser.de/downloads/debian: typo

### ISSUE THREAD

**Issue by CharlesMAtkinson** [iridium-browser/tracker#235]
Wrongly, on https://iridiumbrowser.de/downloads/debian "System requirements: • Ubuntu 16.04+ (x86_64)"

**Comment by souldanger** [comment]
I have tested and can't seem to find any issues...

**Comment by CharlesMAtkinson** [comment]
> I have tested and can't seem to find any issues...
Sorry for the noise.  I thought the page was for Debian rather than Debian-based systems
