### ISSUE TITLE
Will Not Install in RHEL 7.6

### ISSUE THREAD

**Issue by quantum77** [iridium-browser/tracker#240]
Can not install as dependencies are libs newer than come with the most up-to-date install.

Resolving Dependencies
--> Running transaction check
---> Package iridium-browser.x86_64 0:2019.04.73-1.fc29 will be installed
--> Processing Dependency: control-center-filesystem for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libm.so.6(GLIBC_2.27)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libpipewire-0.2.so.1()(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Running transaction check
---> Package control-center-filesystem.x86_64 1:3.28.1-4.el7 will be installed
---> Package iridium-browser.x86_64 0:2019.04.73-1.fc29 will be installed
--> Processing Dependency: libm.so.6(GLIBC_2.27)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Processing Dependency: libpipewire-0.2.so.1()(64bit) for package: iridium-browser-2019.04.73-1.fc29.x86_64
--> Finished Dependency Resolution
--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies
Error: Package: iridium-browser-2019.04.73-1.fc29.x86_64 (iridium-browser)
           Requires: libm.so.6(GLIBC_2.27)(64bit)
Error: Package: iridium-browser-2019.04.73-1.fc29.x86_64 (iridium-browser)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package: iridium-browser-2019.04.73-1.fc29.x86_64 (iridium-browser)
           Requires: libpipewire-0.2.so.1()(64bit)
Error: Package: iridium-browser-2019.04.73-1.fc29.x86_64 (iridium-browser)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: iridium-browser-2019.04.73-1.fc29.x86_64 (iridium-browser)
           Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by ngothan** [comment]
As your log file shows, you have rhel7 (centos7) installed on your machine. The problem is that you installed the wrong Iridium-browser version built for fedora 29

Please use the correct repro to installl the Iridium-browser version which is built for rhel7 (centos7)

wget -O /etc/yum.repos.d/iridium-browser.repo https://dl.iridiumbrowser.de/epel7/iridium-browser.repo
yum install iridium-browser

**Comment by quantum77** [comment]
Please be advised that your instructions are here:
https://iridiumbrowser.de/downloads/rhel

# wget -O /etc/yum.repos.d/iridium-browser.repo https://dl.iridiumbrowser.de/epel7/iridium-browser.repo
--2019-05-14 08:13:45--  https://dl.iridiumbrowser.de/epel7/iridium-browser.repo
Resolving dl.iridiumbrowser.de (dl.iridiumbrowser.de)... 88.198.85.193, 2a01:4f8:222:6c9::f3
Connecting to dl.iridiumbrowser.de (dl.iridiumbrowser.de)|88.198.85.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 259
Saving to: ‘/etc/yum.repos.d/iridium-browser.repo’

100%[========================================================================================================================================================================>] 259         --.-K/s   in 0s      

2019-05-14 08:13:47 (17.1 MB/s) - ‘/etc/yum.repos.d/iridium-browser.repo’ saved [259/259]


This results in /etc/yum.repos.d/iridium-browser.repo:
[iridium-browser]
name=Copr repo for iridium-browser by than
baseurl=https://dl.iridiumbrowser.de/epel$releasever/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://dl.iridiumbrowser.de/epel$releasever/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1


... and:
# dnf install iridium-browser
Extra Packages for Enterprise Linux 7 - x86_64                                                                                                                                    0.0  B/s |   0  B     00:00    
ELRepo.org Community Enterprise Linux Repository - el7                                                                                                                            0.0  B/s |   0  B     00:00    
ELRepo.org Community Enterprise Linux Kernel Repository - el7                                                                                                                     0.0  B/s |   0  B     00:00    
Copr repo for iridium-browser by than                                                                                                                                             0.0  B/s |   0  B     00:00    
Oracle Linux / RHEL / CentOS-7 / x86_64 - VirtualBox                                                                                                                              0.0  B/s |   0  B     00:00    
Adobe Systems Incorporated                                                                                                                                                        0.0  B/s |   0  B     00:00    
Copr repo for wireguard owned by jdoss                                                                                                                                            0.0  B/s |   0  B     00:00    
CentOS-7 - Base                                                                                                                                                                   0.0  B/s |   0  B     00:00    
CentOS-7 - Updates                                                                                                                                                                0.0  B/s |   0  B     00:00    
CentOS-7 - Extras                                                                                                                                                                 0.0  B/s |   0  B     00:00    
Nux.Ro RPMs for general desktop use                                                                                                                                               0.0  B/s |   0  B     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides libc.so.6(GLIBC_2.28)(64bit) needed by iridium-browser-2019.04.73-1.fc29.x86_64
  - nothing provides libm.so.6(GLIBC_2.27)(64bit) needed by iridium-browser-2019.04.73-1.fc29.x86_64
  - nothing provides libstdc++.so.6(GLIBCXX_3.4.20)(64bit) needed by iridium-browser-2019.04.73-1.fc29.x86_64
  - nothing provides libstdc++.so.6(GLIBCXX_3.4.21)(64bit) needed by iridium-browser-2019.04.73-1.fc29.x86_64
  - nothing provides libpipewire-0.2.so.1()(64bit) needed by iridium-browser-2019.04.73-1.fc29.x86_64

**Comment by ngothan** [comment]
I checked the rpms in the download directory and found that unfortunately the wrong rpms were copied. We are in the process of fixing the problem.

You can temporarily install iridium-browser from my Repo

wget -O /etc/yum.repos.d/iridium-browser.repo https://than.fedorapeople.org/epel7/iridium-browser/iridium-browser.repo

**Comment by quantum77** [comment]
No ability to use proxy?  Dealkiller.

My whole LAN routes through a VPN, and I need a browser that can proxy to a direct connection through the router. (Squid)

iridium-browser -h has nothing.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by asim13june** [comment]
@ngothan who are you and how reliable is your repository? 

wget -O /etc/yum.repos.d/iridium-browser.repo https://than.fedorapeople.org/epel7/iridium-browser/iridium-browser.repo

I am also having issue downloading and installing the browser. Please check the below log:
[root@VisualConcepts ~]# wget -O /etc/yum.repos.d/iridium-browser.repo https://dl.iridiumbrowser.de/epel7/iridium-browser.repo
[root@VisualConcepts Downloads]# yum install iridium-browser
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror-hk.koddos.net
 * epel: ftp.riken.jp
 * extras: mirror-hk.koddos.net
 * updates: mirror-hk.koddos.net
https://dl.iridiumbrowser.de/fedora_7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

No package iridium-browser available.
Error: Nothing to do

**Comment by ngothan** [comment]
I am Iridium browser package maintainer for Fedora and Epel7. The https://dl.iridiumbrowser.de/epel7/iridium-browser.repo is the mirror of my repos.

I asked the admin of dl.iridiumbrowser.de to fix it a long time ago. Unfortunately the problem is still there!

**Comment by asim13june** [comment]
Hi @ngothan 

I tried with 
`wget -O /etc/yum.repos.d/iridium-browser.repo https://than.fedorapeople.org/epel7/iridium-browser/iridium-browser.repo`

Check the below log:
```
[root@VisualConcepts ~]# wget -O /etc/yum.repos.d/iridium-browser.repo https://than.fedorapeople.org/epel7/iridium-browser/iridium-browser.repo
--2019-07-27 03:08:10--  https://than.fedorapeople.org/epel7/iridium-browser/iridium-browser.repo
Resolving than.fedorapeople.org (than.fedorapeople.org)... failed: Name or service not known.
wget: unable to resolve host address ‘than.fedorapeople.org’
```
Is there a way i can download the files on my computer and install them locally.

**Comment by ngothan** [comment]
please check your network setting. I can download it without any problem!
