### ISSUE TITLE
I cannot disable and remove extensions

### ISSUE THREAD

**Issue by smaragdus** [iridium-browser/tracker#241]
I am using the latest version of [Iridium](https://iridiumbrowser.de/) - **2019.4.73.0**:

![Iridium 2019 4 73 0 - 2019-05-18 - 002](https://user-images.githubusercontent.com/9025757/57969530-8d9a8680-7980-11e9-9517-7752d5318a30.png)

on Windows 8 x64 (in portable mode) and I cannot disable and remove extensions.

Disabling extensions does not work- I disable an extension, close 'Settings', open 'Settings' again, the disabled extension is enabled again.

Removing extensions does not work either- clicking on 'Remove' button does nothing- it does not remove the extension.

Please confirm the problem.

**Comment by souldanger** [comment]
please check our FAQ - see "WHY DO EXTENSIONS NOT UPDATE AUTOMATICALLY AND WHY DOES THE EXTENSION PANEL NOT FULLY WORK?"

**Comment by smaragdus** [comment]
@souldanger 

Thanks, I read the [FAQ](https://iridiumbrowser.de/faq) but I think that there is no way to disable extension from toolbar menu- it can only be hidden or removed but not disabled. Is there a way to disable an installed extension without removing it?

**Comment by souldanger** [comment]
unfortunately, disabling an extension does not work. Adding / removing is currently all that can be done.

**Comment by smaragdus** [comment]
@souldanger 

Thank you for the immediate response, Have a nice day!

**Comment by souldanger** [comment]
@smaragdus 
This is an unintentional side effect, that occured, when we were blocking several connections to Google services.

**Comment by smaragdus** [comment]
@souldanger 

> This is an unintentional side effect, that occured, when we were blocking several connections to Google services.

I supposed so. That was why I asked for some workaround/hack. Anyway for me privacy is more important than convenience.

Off-topic- I would like to know whether it would be possible in the future to allow installing extensions which are not published in Chrome store directly from .CRX files without unpacking them ([related issue](https://github.com/erickutcher/httpdownloader/issues/58)).

**Comment by souldanger** [comment]
@smaragdus 
We are privacy and security focused and therefore do not spend a lot of time on extensions.
The issue you described is a Chromium issue and has nothing to do with the privacy enhancements and security patches applied by Iridium Browser.
However, we are always open to suggestions, improvements and contributions. If you find a solution for this please feel free to let us know.
