### ISSUE TITLE
Unable to add PGP key to Ubuntu Ring

### ISSUE THREAD

**Issue by scottbourne** [iridium-browser/tracker#242]
When executing "wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -" 
as indicated on https://iridiumbrowser.de/downloads/debian 
on my 18.04 system, 
the result is: gpg: no valid OpenPGP data found.
and I am unable to install Iridium

**Comment by zeonn** [comment]
The website https://iridiumbrowser.de hasn't been up and running for two days

**Comment by souldanger** [comment]
@zeonn 
Thanks for the heads up!
The website will be up again soon.

**Comment by scottbourne** [comment]
Web site back up, added key to keyring, installed iridium - all is good!
