### ISSUE TITLE
Update Debian binary to Chromium 73

### ISSUE THREAD

**Issue by stxm** [iridium-browser/tracker#247]
Hey 

I have noticed that the Debian binary is still at Chromium 71.
Could you post a status update on the Debian build ?

**Comment by longsleep** [comment]
Well I assume you mean Debian 9 - due to this bring very old the build currently does but function there. Since my time is very limited this might or might not change when I work on the next build. You can manually resolve dependency and install the latest iridium build though.

**Comment by souldanger** [comment]
Our Debian developer has moved on and we are looking for a new developer ever since.
Once we found someone this will be posted on our website.
Thank your for your understanding.
