### ISSUE TITLE
Extension does not turn off

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#249]
Feedback: I'm using a Windows 8.1 which Iridium version is 2019.04.73.0, so my issue is when I turn off an Extension it does not turn off instead it turns on again. Please fix it at a newest version. It's happening at all 2018/2019 versions and all Windows Computers I have tried. Thank you.

**Comment by Flaflo** [comment]
This is intentionally, I think.

**Comment by souldanger** [comment]
Please check out our [FAQ](https://iridiumbrowser.de/faq) and look for "WHY DO EXTENSIONS NOT UPDATE AUTOMATICALLY AND WHY DOES THE EXTENSION PANEL NOT FULLY WORK?"
