### ISSUE TITLE
Certificate and apt errors - again

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [iridium-browser/tracker#251]
When updating my Linux system (details of which below) via `apt` I see the following error related to your repository. 

```
E: The repository 'https://downloads.iridiumbrowser.de/deb stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

I have had this problem and also other similar problems before. Often. Moreover just now in visiting your website Firefox shows a certificate error.

If the current maintainer(s) of your admirable and useful project cannot keep certificates and repositories working, then perhaps you should get some new help.

My system:

OS: Linux Mint 19.2 Tina x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.2.13-050213-generic 
DE: Cinnamon 4.2.4 
Terminal: xfce4-terminal 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 

Irridium: Version 2019.04 (Developer Build) Built on Ubuntu 16.04, running on LinuxMint 19.2 (64-bit)

**Comment by hovancik** [comment]
similar issue with website (in Firefox)

```
Did Not Connect: Potential Security Issue

Firefox detected an issue and did not continue to iridiumbrowser.de. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely.

What can you do about it?

iridiumbrowser.de has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

Your computer clock is set to 12/17/2019. Make sure your computer is set to the correct date, time, and time zone in your system settings, and then refresh iridiumbrowser.de.

If your clock is already set to the right time, the website is likely misconfigured, and there is nothing you can do to resolve the issue. You can notify the website’s administrator about the problem.
```

**Comment by LinuxOnTheDesktop** [comment]
I too am having the problem again. I suspect that Iridium is rolling out its files to the servers. For, I just got an Iridium update on Windows. It is a shame that roll out is not faster. It is a shame too that the Iridium developers seem to ignore some of the issues filed on this bugtracker.

**Comment by souldanger** [comment]
The issue has been solved!
Thanks for pointing this out.

**Comment by LinuxOnTheDesktop** [comment]
Good! However, I don't see the latest Iridium (2019.11) in the updates for my Linux machine and I believe I should. I believe I should because: (1) my Windows machine has that version (admittedly via manual download, I think); (2) the error message that updating the Linux machine used to give - and which, indeed, it gives no longer - suggests than an update was in the pipeline. Still, perhaps the repositories are being stocked silently and the update will arrive soon.
