### ISSUE TITLE
Adding ecosia as a search engine option?

### ISSUE THREAD

**Issue by lachlanallison** [iridium-browser/tracker#254]
Ecosia is a search engine aimed at plating trees around the world but they also claim to be privacy friendly. It would be nice to have this search engine as a built in option in Iridium. However I am not sure if the privacy of this search engine is comparable to the other built in options.
https://info.ecosia.org/privacy

**Comment by souldanger** [comment]
Thanks for the recommendation!
We will review and might add it to future releases.
