### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by pfackelmann** [iridium-browser/tracker#255]
„iridium-browser_2019.11-0_macos.dmg“ kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann.
Diese Software muss aktualisiert werden. Wende dich an den Entwickler, um weitere Informationen zu erhalten.

Regards

Peter

**Comment by souldanger** [comment]
Hi Peter
Iridium ist "nur" signiert, aber nicht von Apple "notarisiert". Daher muss unter Sicherheit auf "App Store und verifizierten Entwickler" umgestellt werden: https://support.apple.com/de-de/HT202491

![macOS_screenshot](https://user-images.githubusercontent.com/10036776/71899037-2aea3b00-315b-11ea-9dd1-b7f0fbdfd7ab.png)
