### ISSUE TITLE
Build instructions missing 'gn gen' step, and config switches

### ISSUE THREAD

**Issue by androticus** [iridium-browser/tracker#256]
Forgive me if I've missed something...
I followed the build instructions for Iridium on Linux (btw, there were a few problems, such as git url redirects not working, which I overcame...)
In the Chromium build instructions, there is the following sequence:
`$ gclient runhooks`
`$ gn gen out/Default #or whatever folder you will use`
`$ autoninja -C out/Default chrome`
But the middle step is missing in the Iridium instructions, and the subsequent autoninja step fails. The gn gen step creates the configuration file args.gn, whose flags are an important part of the build.
1. Is the args.gn file used by the Iridium team available somewhere? 
2. Can you update the build instructions to include this step (and also change the git locations from the .de domain to the github location?)

Thanks! Thanks for creating Iridium.

**Comment by jengelh** [comment]
>But the middle step is missing in the Iridium instructions

I wonder which build instructions you refer to – I am not aware that we provide any.

**Comment by androticus** [comment]
https://github.com/iridium-browser/iridium-browser-dev

**Comment by androticus** [comment]
Also, from the very top panel on your homepage: ;)
https://iridiumbrowser.de/

> In addition, all our builds are reproducible and modifications are auditable, setting the project ahead of other secure browser providers.

**Comment by jengelh** [comment]
>iridium-browser-dev

I forgot that even exists. My personal scribblings are in `BUILD-IRID.txt` in the main repo.

>reproducible

I suppose that is only applicable to the SRPM and debsource.

**Comment by androticus** [comment]
Oh, thanks, that was helpful. but I am getting this failure trying to run the gn gen step in your file:
`ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/mobiledev/iridium/src/out/Release/
Command: python /home/mobiledev/iridium/src/build/config/linux/pkg-config.py libpipewire-0.2
Returned 1.
stderr:

Package libpipewire-0.2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpipewire-0.2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpipewire-0.2' found
Could not run pkg-config.
`

**Comment by jengelh** [comment]
>Package libpipewire-0.2 was not found in the pkg-config search path

Yup, you will have to install the dependencies as they are mentioned by gn one by one.

**Comment by androticus** [comment]
Ok, but I ran the src/build/install-build-deps.sh script; there is no mention of pipewire in that script, nor on the build instruction page listing all the dependencies. I've been unable to even understand how to get that. What do I need to install for that, and how? It is not in apt repo, and when I search, I just find things like plugins for gstreamer.

**Comment by jengelh** [comment]
Perhaps Google does not update the install-build-deps script either; I myself have never used it.
Or, you can turn off pipewire - just modify the call to gn.

Well, at least pipewire exists in Debian, https://packages.debian.org/search?keywords=pipewire

**Comment by androticus** [comment]
So I had to remove these things from the gn line for that step to succeed.
* remove libpipewire deps
* remove use_system_harfbuzz=true
* remove  use_vaapi=true
But almost immediately on starting the compile, I got a bunch of these -M errors:

`[2/23458] CXX obj/base/base_static/base_switches.o
FAILED: obj/base/base_static/base_switches.o 
-MMD -MF obj/base/base_static/base_switches.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-pointer -g1 -fvisibility=hidden -O2 -fno-ident -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../base/base_switches.cc -o obj/base/base_static/base_switches.o
/bin/sh: 0: Illegal option -M
`

**Comment by jengelh** [comment]
I think $CXX may be empty in your case, causing -M to be treated differently.
Please use `export CC=gcc CXX=g++ AR=ar NM=nm` as per BUILD-IRID.txt.

**Comment by androticus** [comment]
oops... ok, fixed that up -- it started compiling, got through quite a few files(several thousand) before I left for night, but then I got a "subcommand failure" error -- copied entire console of trying to restart it, below, in case the info is helpful:

`mobiledev@chromebuilder6:~/iridium/src$ ninja -C out/Release chrome chrome_sandbox
ninja: Entering directory `out/Release'
[15/10474] CXX obj/services/tracing/lib/track_event_json_exporter.o
FAILED: obj/services/tracing/lib/track_event_json_exporter.o 
g++ -MMD -MF obj/services/tracing/lib/track_event_json_exporter.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/boringssl/src/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -I../../third_party/protobuf/src -Igen/protoc_out -Igen/third_party/perfetto -Igen/third_party/perfetto -Igen/third_party/perfetto -Igen/third_party/perfetto -Igen/third_party/perfetto -Igen/third_party/perfetto -Igen/third_party/perfetto -I../../third_party/protobuf/src -Igen/third_party/perfetto -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -fvisibility=hidden -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../services/tracing/perfetto/track_event_json_exporter.cc -o obj/services/tracing/lib/track_event_json_exporter.o
../../services/tracing/perfetto/track_event_json_exporter.cc: In member function ‘base::Optional<tracing::JSONTraceExporter::ScopedJSONTraceEventAppender> tracing::TrackEventJSONExporter::HandleLegacyEvent(const LegacyEvent&, const string&, int64_t)’:
../../services/tracing/perfetto/track_event_json_exporter.cc:790:10: error: could not convert ‘builder’ from ‘tracing::JSONTraceExporter::ScopedJSONTraceEventAppender’ to ‘base::Optional<tracing::JSONTraceExporter::ScopedJSONTraceEventAppender>’
   return builder;
          ^~~~~~~
../../services/tracing/perfetto/track_event_json_exporter.cc: In member function ‘int64_t tracing::TrackEventJSONExporter::ComputeTimeUs(const perfetto::protos::TrackEvent&)’:
../../services/tracing/perfetto/track_event_json_exporter.cc:191:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../../services/tracing/perfetto/track_event_json_exporter.cc: In member function ‘base::Optional<long int> tracing::TrackEventJSONExporter::ComputeThreadTimeUs(const perfetto::protos::TrackEvent&)’:
../../services/tracing/perfetto/track_event_json_exporter.cc:205:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../../services/tracing/perfetto/track_event_json_exporter.cc: In member function ‘base::Optional<long int> tracing::TrackEventJSONExporter::ComputeThreadInstructionCount(const perfetto::protos::TrackEvent&)’:
../../services/tracing/perfetto/track_event_json_exporter.cc:220:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../../services/tracing/perfetto/track_event_json_exporter.cc: In function ‘const char* tracing::{anonymous}::ThreadTypeToName(perfetto::protos::ThreadDescriptor::ChromeThreadType)’:
../../services/tracing/perfetto/track_event_json_exporter.cc:63:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
cc1plus: warning: unrecognized command line option ‘-Wno-packed-not-aligned’
[24/10474] CXX obj/services/tracing/pu.../track_event_thread_local_event_sink.o
ninja: build stopped: subcommand failed.
mobiledev@chromebuilder6:~/iridium/src$ 
`

**Comment by jengelh** [comment]
iridium-browser-dev now points to the README.md in the source tree.
