### ISSUE TITLE
Password in plain text

### ISSUE THREAD

**Issue by maxlivi** [iridium-browser/tracker#257]
I am using Linux and iridium:
Version 2019.04 (Developer Build) Built on Ubuntu 16.04, running on (64-bit)

```

sqlite3 ./Login\ Data 
.mode line
SELECT * from logins ;
```

I see the passord in plain text.

**Comment by Egraveline** [comment]
when people say to only store hashes of passwords it is usually meant in the context of servers, machines not owned by you shouldn't contain your password, but a machine owned by you can store a password in plain text. I mean what do you expect, a master password for all your passwords? how would you store that? yes that would be important if your passwords were being synced across different accounts, and in that case the passwords are hashed on google servers and not stored in plain text.

The assumption is, you shouldn't be doing things that require security on machines that are comprised, and if you want added security then you need to use something along the lines of keepass.

At least that's my understanding, I could be wrong.

**Comment by myspaghetti** [comment]
>what do you expect, a master password for all your passwords?

That would be the [correct implementation](https://support.mozilla.org/en-US/kb/where-are-my-logins-stored#w_the-firefox-password-manager), yes. macOS and Android have a keychain that encrypts all passwords and other sensitive data, and it is unlocked with the user's login password. If the OS doesn't supply a secure keychain, then passwords need to be encrypted with a master password.

**Comment by Egraveline** [comment]
@myspaghetti But all those examples are for services built for syncing your password across multiple devices. If your hard drive is encrypted the idea is that it should be safe. Assuming you are using an non-compromised machine. Iridium doesn’t sync your passwords. If you are leaving your computer unlocked in an area for someone with unauthorized access to be able to get it yes you should certainly have a master password system such as keepass like I said. 

I suppose it would be a good thing for them to implement anyway though.

**Comment by myspaghetti** [comment]
None of those examples are for synching your password across multiple devices. You CAN sync your macOS, Android, or Firefox passwords, but even if they're not synced they need to be encrypted by a master password.

**Comment by Egraveline** [comment]
That’s what I mean, with syncing they are essential, without syncing they serve the same purpose as keepass.

**Comment by myspaghetti** [comment]
That's not what you said, and it doesn't change that encrypting passwords with a master passwords is still the correct implementation. It's not "for services built for syncing your password across multiple devices", it's for storing the passwords at rest on your device.
