### ISSUE TITLE
Allow third party extensions

### ISSUE THREAD

**Issue by metapea** [iridium-browser/tracker#258]
Please allow third party extension to be installed.
When i tried to "load unpacked" it in dev mode, it's works for a short time until i close the browser. Which then gets deleted every time in 1 minute or two after opening.

And with .crx doesn't even worked at all (https://i.imgur.com/s6TvzTp.png). All it's does is turn the extension off permanently and says " This extension is not listed in the Chrome Web Store and may have been added without your knowledge". Thanks to that, i can't remove it at all (since you can't uninstall it if not in the top menu. I tried to get rid of it by deleting the extension's main folder but but that didn't work). 

I tired to do the other ways like with adding google's policy templates to whitelist and using regedit to whitelist, but sometimes they don't work at all and it's take a while to get it working (if you're luck), i was fine until now using that workaround.

**Comment by metapea** [comment]
Also can you disable [this](https://i.imgur.com/KxjoULm.png)

**Comment by souldanger** [comment]
did you try to install exetnsions manually and via the webstore?

**Comment by metapea** [comment]
There's some extensions that are not in the webstore, _aka third party extensions_

**Comment by souldanger** [comment]
Please accept my apologies!
I meant to say;

> did you try to install exetnsions manually and _NOT_ via the webstore?

Iridium Browser does not block certain extensions - it blocks all extensions that do not comply  with Iridium's privacy/security enhancements.

**Comment by metapea** [comment]
**This has nothing to do with Iridium's blocking extensions on the webstore or Iridium's auto-block.**
You can't install _any third party extensions_ in chrome or iridium, even if it's open source or on github itself.
I know this can be fix since ungoogled chromium and forks of chromium fully allows _third party extensions to install_

**Comment by souldanger** [comment]
Thanks for the info, but we have no intention whatsoever to make Iridium more insecure.
Thank you for your understanding.

**Comment by metapea** [comment]
But this isn't about making Iridium more insecure.
For context, google chrome has been blocking any extension that is not from the google webstore,  meaning if you want an extensions from github, you can't. you can install extensions by the webstore.
Sorry, but is this is a well known thing that is happening for while now. Google can get rid for any extensions that they disagree with and now this is giving open source extensions like AdNauseam or any extension that google disagrees a hard time.

If you keep this Closed, then i will just remake this issue with better context. 
Also please don't be passive-agaisive, sorry if i may come off as rude but i already told you this issue is unrelated to #271 & 277 (this was even made months before that issue), i've already told you i'm not talking about suspicious extensions from the webstore, but extensions that not on the webstore as a whole. Since now if you're leaving this issue unfixed, there will be no alternative for users of iridium, but to use the google webstore. like you said on #272 "it sends much more user data", the webstore itself is no different. Allowing third party extensions, so users can have an alternative and manually install from github or any other site, instead of only using the webstore from google themselves (which is what Iridium doing right now) isn't making Iridium "more insecure".
I hope _you_ will _understand._
