### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mrkaban** [iridium-browser/tracker#262]
The BSD license is indicated in the source code, but the license is not specified anywhere in the license itself. It happens that the source code has one license, and the compiled version is completely different. Please indicate the license in the program.

**Comment by souldanger** [comment]
see chrome://credits/ for any and all licenses.

**Comment by mrkaban** [comment]
I wanted to add the program to a site with 1,500-2,000 unique visitors per day, but if you can’t specify a license for the program, and not for composite libraries, then it is not interesting.

**Comment by souldanger** [comment]
Again, any and all licenses and credits for Iridium Browser which is based on Chromium can be found, if you copy the following into the address bar of your Iridium/Chromium based browser: ```chrome://credits/```
Thank you for your understanding!
