### ISSUE TITLE
google maps faulty HTML rendering

### ISSUE THREAD

**Issue by inquiribus** [iridium-browser/tracker#263]
https://www.google.com/maps/dir/Amarillo,+TX/Little+Rock,+AR/@34.3148994,-101.1737474,7z/data=!4m16!4m15!1m5!1m1!1s0x870148d4b245cf03:0xd0f3d11c6836d2af!2m2!1d-101.8312969!2d35.2219971!1m5!1m1!1s0x87d2a134a11f569b:0x3405f5100df35b17!2m2!1d-92.2895948!2d34.7464809!2m1!2b1!3e0

the above link, on Iridium

Version 2019.04 (Developer Build) Built on Ubuntu 16.04, running on Ubuntu 18.04 (64-bit)

running on VMware player 15.5.2 build-15785246 (non accelerated graphics, known to work well otherwise) hosted on 

$ uname -a
Linux  4.15.0-1076-oem #86-Ubuntu SMP Wed Mar 4 05:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

(plain vanilla Intel graphics)

produces this incorrect rendering of google maps (note the travel time/distance boxes, one is well formed, two are not) for map:

![Screenshot from 2020-03-27 10-25-09](https://user-images.githubusercontent.com/52505942/77777784-a9959c80-7015-11ea-92e8-04b2dfb4658c.png)

and this worse rendering for satellite:

![Screenshot from 2020-03-27 10-30-16](https://user-images.githubusercontent.com/52505942/77778074-1741c880-7016-11ea-8b41-fba3fade1321.png)

Given that the setup (hardware+hypervisor) is known to be stable, the browser engine is probably at fault.

**Comment by souldanger** [comment]
Hello
could you please try  the latest version and let us know if te issue persists.
I have not been able to reproduce the faulty gmap problem.
Thanks
