### ISSUE TITLE
Unable to remove / delete / disable extensions

### ISSUE THREAD

**Issue by patrickhgb** [iridium-browser/tracker#264]
*App version: *
2020 01 v79 64bit
Windows 10 LTSC 64bit

Issue/Request:
I cannot remove extensions with iridium portable

Steps to reproduce (if applicable)

    Install an extension from google store (ie: ublock origin)
    Open extensions tab and click uninstall/delete (does not work)

Other details:

Have tried older build versions and issue seems persistent

**Comment by souldanger** [comment]
Hi,
please see our FAQ: "WHY DO EXTENSIONS NOT UPDATE AUTOMATICALLY AND WHY DOES THE EXTENSION PANEL NOT FULLY WORK?"
Let us know if you need any further help.

**Comment by Flashwalker** [comment]
How can i delete extension that has no icon?
