### ISSUE TITLE
site download page 404

### ISSUE THREAD

**Issue by omar-mahfooz** [iridium-browser/tracker#265]
Dear Iridium, 

your site download button , links to a page with no download, please assist. It only displays a 404 error

**Comment by souldanger** [comment]
Thanks for the heads-up!
Obviously something went wrong on our end - it will be fixed momentarily.

**Comment by narcisgarcia** [comment]
Please attend packaging patch from issue #208 and GNU/Linux packages will be usable with following Download pages instructions.
