### ISSUE TITLE
How to remove extensions completely

### ISSUE THREAD

**Issue by Marek33** [iridium-browser/tracker#266]
It seems that I cant remove any extension, even if its written in FAQ, that I can. So, I removed the two folders, which only makes the extensions corrupted, but I would like to remove them completely, since I no longer need them. I'm not sure, if I need to check something in the **Extension Rules** or **Extension State**, but I don't want to corrupt other extensions.

**Comment by souldanger** [comment]
Please uninstall extensions from the top right (next to address bar) of the browser window. If this does not work, what extensions are you referring to?

**Comment by Marek33** [comment]
By top right, you mean clicking on those three dots, and then clicking on the more tools, and extensions? I did exactly that, and I opened the chrome://extensions, but when I click on the **Remove** button, it doesn't remove them. No matter, if I have Developer Mode on, or off. I have it on, because the **YouTube Classic** wouldn't work otherwise.

I want to remove the **YouTube Switch**, which I no longer need, since the YouTube Classic is way better.

**Comment by souldanger** [comment]
By top right I meant the actual exension icon - if you click on these you should be able to remove the extension.

**Comment by Marek33** [comment]
Yes, that worked! Thank you very much! _I never removed extensions, that way, so I didn't even know about it._ Thou, if the classic removing doesn't work, since it _calls the Google_, this one doesn't do it?

And, if I want to update an extension how exactly can I do it? Do I only need to extract the files to the Iridium user folder?

**Comment by souldanger** [comment]
Update any extensions manually by downloading and installing the latest version. Click on the extension icon next to the address bar to access options or to remove any extension.
You may want to backup your extensions settings before updating and reinsert these once updates have been installed. The settings can be found in Windows at C:\Users\%user%\AppData\Local\Iridium\User Data\Default\Local Extension Settings.

**Comment by Marek33** [comment]
I understand and thanks for the info!

I did update the uMatrix like this, but I was afraid to update the uBlock Origin, since I don't want to lose the high number of blocked requests which I have.

**Comment by souldanger** [comment]
no problem!
You may want to backup your extensions settings before updating and reinsert these once updates have been installed. The settings can be found in Windows at
C:\Users\%user%\AppData\Local\Iridium\User Data\Default\Local Extension Settings
This way you don't lose any data of your extensions.
