### ISSUE TITLE
Question Please help me

### ISSUE THREAD

**Issue by qw123wh** [iridium-browser/tracker#267]
Hi there is a method to enable the translation of web pages on iridium?  I have enabled page translation in the settings but it doesn't work.  As an alternative, do you know any extension to translate entire web pages?

**Comment by souldanger** [comment]
Iridium Browser does not ship with a built-in language translator.
Please check [chrome webstore ](https://chrome.google.com/webstore/category/extensions) for any extension that serves your needs..
