### ISSUE TITLE
Is enterprise/business setup possible

### ISSUE THREAD

**Issue by nakal** [iridium-browser/tracker#268]
Hi,

we are considering using Iridium for our larger setup. It is very important that we can setup Iridium all our users with a homepage location and various other settings. For Chrome there are [policy templates](https://cloud.google.com/chrome-enterprise/browser/download/#download) that we can use. Unfortunately, they apparently don't work with Iridium.

Is there any other way to manage user settings? We've tried to guess some registry keys, too. We haven't found any effects on Iridium.

Thanks in advance.

**Comment by souldanger** [comment]
Hi Nakal,
we are working on a enterprise solution but no release date has been set.

*Iridium Browser for Enterprise provides IT with business capabilities for distribution and expansion via a GPO policy, a large variety of user and device policies through ADM / ADMX, a customized build with branding as well as limited toubleshooting assistance and admin support.*

We will announce on website and social media once available.

**Comment by nakal** [comment]
Ok. Thank you very much for the information.
