### ISSUE TITLE
Loading of tabs

### ISSUE THREAD

**Issue by johbru0** [iridium-browser/tracker#269]
I setup my Iridium browser to load some tabs when it boots. I'm noticing that the tabs just keep loading unless i click the x to stop the page from loading and then click the reload command. This causes the loading to stop and then re-load successfully but its a very manual method when you have a lot of tabs that just keep loading. I did just upgrad to Iridium 2020.04.81

I'm new to Iridium but like it a lot. I will probably continue to use it but this loading issue iritate me. Anyone also having this problem and how did you fix it. I did test out other Chrome based browsers to see if they were also having this issue but its on Iridium. Finally, i did uninstall and re-install to make sure there were no corrupted files.

Thanks,
John

**Comment by souldanger** [comment]
Hi John
tried to reproduce with 20 open tabs but can't seem to find any problem.
Do you possibly have any extensions installed that block loading for some reason?
Did you change any settings?
Did you try to turn off hardware acceleration?

Thanks!

**Comment by johbru0** [comment]
Souldanger, thanks for responding and trying to hellp. I've never used GitHub so i'm not real experienced at this type of communication

I usually load inside a sandbox to better protect my internet usuage from the cyberthieves and their ransomeware but even if i don't load it inside Sandboxie the tabs justs show loading. To get them to finish loading i have to chose each tab one by one and hit crtl R and then it completes the loading. I'm an accountant so not the most smart techie guy around. 

I do use some privacy extensions such as Adblock Plus - free ad blocker, AdBlocker Ultimate, Blur, Cookie AutoDelete, Dark Reader, Decentraleyes, Disconnec, Ghostery – Privacy Ad Blocker, Hide Incognito Mode, HTTPS Everywhere, LastPass, Privacy Badger, TunnelBear VPN, uBlock Origin and Weather. 

When i first started to use Iridium as my browser of choice it would load the tabs with no problems. Then, a few days ago all the tabs just kept saying loading but never finished until i picked one tab and hit Ctrl R and then they would complete the loading. I haven't customized any of the settings and i wouldn't know how to turn off hardware acceleration so i definitely didn't do that.

I tried to copy/paste an image but was unsuccessful.

John

**Comment by souldanger** [comment]
Hi John
most of us are using some of the same extensions as you do, but as you load a whole bunch of ad blockers, this might be the reason.  Therefore our suggestion would be to try to temporarily loose a few of them to see if there is any improvement.
I can confirm that LastPass, HTTPS Everywhere, Ghostery, uBlock origin do not cause any issues.

Hardware acceleration can be turned on or off in chrome://settings/ > Advanced >System.
In Settings > On startup you can also set 'Open a specific page or set of pages'.

We have not changed anything since the release of version 2020.04 and we have absolutely no way of changing anything on your machine. The browser is designed to not call us or any other central services, which means once installed it is all yours.

**Comment by johbru0** [comment]
Unfortunately i am having nothing but problems using Iridium as my browser of choice. I tried to remove both adblocker extensions per your suggestion and the browser does not respond and does not allow me to delete them. If i then try to move the bar to the right it does not retain the change so in essence extensions are no longer a workable system. I then have tried to uninstall the entire browser thinking that it would be me a fresh copy of the browser w/o any tabs or extension so i can re-set it up but instead it brings back all the tabs and the remaining extensions that i cannot remove and then re-install. Its like something is corrupted yet i cannot cleanly remove from my system. If these problems continue i w/ be forced to use another browser that actually works as this one no longer works. Everything is now bonkers on it

**Comment by souldanger** [comment]
well I was under the impression that you had a look in the faq by now - the extension panel is not working, removing extensions must be done by right clicking on the extension's icon on the top right.
However, I understand your decision and wish you all the best finding another solution that satisfies your needs.
Stay safe & private!

**Comment by johbru0** [comment]
I'm an accountant by trade and not a knowledgable High Techie type of user and this is my first time in both Github and using a forum for information. No i did not read a FAQ but i will now. My initial knowledge of Iridium was from a person i highly respect when he recommended Iridium as a top browser so i thought i'd give it a try. I assume most of the people here are loaded with far more computer experience and intuition that i have. I have much to learn. 

FYI, i now have deleted all the extensions, including the 2 adblockers and then re-loaded a freshly installed Iridium browser and the tabs still show loading. Its not a huge issue to hit ctrl-r on each tab to help them load but its a slight iritant and i thought something might be wrong so i posted for the 1st time on this forum to ask for help.

Thank you for your help. I'm learning. 

John

**Comment by souldanger** [comment]
Hi John, 
hope you are keeping well!
Good to see that you are still using Iridium Browser even though there are a few 'hickups', which we understand complicate things a bit. Regardless of any IT knowledge, users expect a fully functional browser, which to be fair, we have not been able to do yet for various reasons.
One is, Iridium Browser is a non-profit organisation, formerly known as "Secure Browser Project", which was and still is run by a handful of security experts and developers, unlike the Chromium project which is run by hundreds if not thousands or almost any other browser out there. 
This is no excuse but explains why we are not perfect yet. I am sure you understand what I mean from an accountant's point of view.
A few other things I need to make you aware of.... the following websites / services will not work with  Iridium - anything that requires 'digital rights management' (DRM) including
- Amazon video
- Disney+
- iTunes
- Netflix
- YouTube
and similar services.

Therefore I can only recommend using a secondary browser for watching videos or listening to music - in all these cases you will need to be logged in to these services and therefore it is pretty much impossible to not transmit any personal data.
Hope that helps.
If you have any other questions or comments, feel free to let me know.
Thanks
Michael

**Comment by johbru0** [comment]
Michael, your beyond-the-call of duty response is noted and appreciated. I tend to support good products i use even if they say "free". I am currently doing that with the Tor browser and will likely do it with Iridium because it has an excellent reputation. I did find the FAQ section and do see the mention of how to delete extensions and i did not notice that until you mentioned it. 

Now i am trying to add back in the deleted extensions but so far no luck but i think the problem is the internet service provider is overwhelmed with all the stay at home workers. I am persistant so i'll keep trying and i anticipate this will become my secondary browser of choice next to SRWare Iron. 

Thank you much for the caution of services that may not work with Iridium which was helpful as i spend a lot of time listening to Podcasts however most of them did work using Iridium, even inside Sandboxie.

Much thanks,
John

**Comment by souldanger** [comment]
Thanks John!
I've also figured out as to why the browser doesn't load pages on restart;
By default, Iridium Browser clears all cookies and website data when you quit the browser.
This can be changed at your own discrection in Settings > Privacy and security > Site settings > Cookies and site data. 
Then uncheck 'Clear cookies and site data when you quit the browser'.
But this is NOT recommended as potiental unwanted tracking cookies from i.e. Facebook and alike will remain on your machine... until you 'Clear browsing data' (Ctrl+h) > advaced (check all)

**Comment by johbru0** [comment]
Michael, again i want to thank you for your support on my 2 "problems"
1) Untitled tabs when loading. I tried your above suggestions on cookies and site data and clear the cookies and site data when i quite the browser just to see if that would correct the loading issue but it still does not load the pages. The tabs just say "untitled" until i hit ctrl-r. I then put the settings back to the way were. I normally clear this and history each night before i turnoff my computer using ccleaner and privacy eraser. 

2) adding back some privacy extensions from Google Store. when i pick an extension, like HTTPS Everywhere, it first  brings up a box that says add extension or cancel and if i say add extension it then says "checking" but never completes the task., 

Not sure why the few privacy extension used to work but now i can't add them back after deleting them but i'm trying to strike a balance between the privacy that Iridium already offers me with the techniques i've been using. Maybe its just a bad habbit really don't need to do anymore.

I am sorry to be such a bother but since i'm an accountant by trade and self-taught to learn how to protect my privacy i try to practice good cyber security higene which is a reason i discovered your browser and i'm just trying to setup the settings similar to other browsers i've used in the past.

Much thanks,
John

**Comment by souldanger** [comment]
Hello John
no worries about asking questions.... from my point of view; rather investigate than making up Trump-like conspiracy theories... :-)

1. If you wipe your history and delete everything with ccleaner, the opened tabs and their respective data is completely deleted from your machine. It is a security feature by Chrome that we didn't touch, as reloading all the 10+ open tabs on restart, may also load bad stuff. I.e. one of the websites might have been hacked over night and strange things may happen without your attention, as you can only see one open tab at a time. So if you want to see loaded webpages on startup - don't delete anything, again, this is not recommended. Then you will see the pages where you left off.
2. This is strange indeed. I use the following extensions and update these once a month;
- HTTPS everywhere
- uBlock origin
- Ghostery
- LastPass
As Iridium Browser blocks connections to the Chrome webstore, updating only works manually, by removing the outdated and installing the lastest version of an extension.
I have just removed HTTPS everywhere to reproduce your issue, but haven't had any issues reinstalling via the webstore. I am not sure why this doesn't work at your end.
Is this just with HTTPS everywhere or with all the exetnsions you are trying to add?

Again, please don't worry about asking questions - we all started somewhere once in life! No one is born a wiz or very stable genius :-). Which means I started somewhere too and the only way to advance is asking and questioning - at least from my point of view.

All the best
Michael

**Comment by johbru0** [comment]
Michael, I replied within your response to mine (indented). Makes it a little longer, sorry

no worries about asking questions.... from my point of view; rather investigate than making up Trump-like conspiracy theories... :-)
	Careful, your sense of humor is showing through, which i appreciate, btw

1) If you wipe your history and delete everything with ccleaner, the opened tabs and their respective data is completely deleted from your machine. It is a security feature by Chrome that we didn't touch, as reloading all the 10+ open tabs on restart, may also load bad stuff. I.e. one of the websites might have been hacked over night and strange things may happen without your attention, as you can only see one open tab at a time. So if you want to see loaded webpages on startup - don't delete anything, again, this is not recommended. Then you will see the pages where you left off.
	Your explanation about using cCleaner makes sense but guess it is catching me offguard as this does not happen with any other browsers that i occasionally use, most of which have Chrome engines (such as SRWare Iron, Vivaldi, Chrome, Epic Privacy Borwser, Brave or Firefox, Waterfox, Palemoon or Opera. The tabs preload with all of them when i load the browser so using cCleaner never occured to me. Its not a big deal and easy enough to change. It was a convenience factor but i don't want to do things to undo the privacy protection that Iridium uses to work properly or protect me

2) This is strange indeed. I use the following extensions and update these once a month;
HTTPS everywhere
uBlock origin
Ghostery
LastPass
As Iridium Browser blocks connections to the Chrome webstore, updating only works manually, by removing the outdated and installing the lastest version of an extension.
I have just removed HTTPS everywhere to reproduce your issue, but haven't had any issues reinstalling via the webstore. I am not sure why this doesn't work at your end.
Is this just with HTTPS everywhere or with all the exetnsions you are trying to add?
	It is strange because, obviously i had extensions that i originally installed when i first discovered Iridium and with Leo LaPorte's recommendation of your wonderful browser i wanted to give it a try. So initially i installed the same extensions i have on my other occasional browsers such as adblock plus, adblocker ultimate (both deleted upon your recommendation), blur, cookie autodelete, dark reader (really helps my eyes as a diabetic), decentraleyes, disconnect, ghostery, hisw inxofniro mode, https everywhere, lastpass (sure miss this one not being able to install), privacy badger, ublock origin, weather (no necessary at all). You can see that the 4 you use i also use which i consider as a compliment to me to use the same ones that you do with your expertise. Installing and manually reinstalling is no big deal unless you can't re-install after you delete them which is what has happened to me. I've tried the common way using the google store https://chrome.google.com/webstore/category/extensions?utm_source=chrome-ntp-icon, typing in the name of the extension, click on add to Chrome and a box pops up and i choose add extension and then it just stalls out there with the message of CHECKING and this is where it doesn't go any further. I've tried uninstalling and re-installing in to elimnate and corrupted files and i'm careful to only try installing extensions outside of the sandoxie program that i use for protection as any browser changes are lost if i'm in a sandbox and then exit. Interesting, the only time i successfully re-installed the extensions i discovered i did it inside sandboxie so naturally i lost them when i exited Sandboxie and since then i only get the CHECKING message and it never completes its task so i can't re-install any of the 4 extensions you lose or the additional 10 extensions i use. The inability to add extensions is for all 14 extensions that i care to add. I attached a screenshot of the CHECKING message so you can see it.
	
	One final thought, i just tried to add an extension, dark theme suite, to SRWare Iron as a chrome engine browser and it easily and successfully installed it and then i manually delted it which means its not a Chrome store problem. I only have this extension problem in using Iridium. I am anxious to somehow getting this feature resolved so i can fully use Iridium

Again, please don't worry about asking questions - we all started somewhere once in life! No one is born a wiz or very stable genius :-). Which means I started somewhere too and the only way to advance is asking and questioning - at least from my point of view.
	Michael, i appreciate your generous help and wonderful attitude. It is so helpful for this non-techie person who so wants to put in the time to protect himself from all the cybercrimals out there with the malware and ransomware they like to use to steal from people. Secondarily, i also wish to protect my privacy as best i can despite the Equifax breech where so much of all our privacy was breeched. It takes good cyber hygiene but i don't mind putting in the time and once you learn it it really doesn't take much time to implement and use compared to the common internet user that practices by cyber hygiene so again, thank you very much for your assistance and suggestions. If i might, do you work or get paid by Iridium for your hard work?
![Loading lastpass in Iridium](https://user-images.githubusercontent.com/65101912/82083821-2b618800-969f-11ea-8e04-bc5088f371d8.png)

![Loading lastpass in Iridium](https://user-images.githubusercontent.com/65101912/82083624-e63d5600-969e-11ea-8498-100295723e90.png)

**Comment by souldanger** [comment]
Hi John
good to hear from you!
We will be diving into the exentsions issue with next release. At this point i am not sure if Google/Chrome changed anything in v81, which would be no surprise or if something went wrong on our end  with the last build. 
I am not a developer myself, I am the web designer, social media uncle and community manager.
However, installing Lastpass works on all my machines and it is truely strange that it does not on yours. As you saw in my reply to a similar question about the portable version, it has something to do with the user profile. It is possible that this is why it works on my side, as I had Lastpass installed with previous version of Iridium and therefore it was in my user profile when updating from v79 to v81... But I am not entirely sure yet and really need to speak to our developers.
Dark Theme;
did you look into `chrome://flags` yet? There is an experimental method called 'Force Dark Mode for Web Contents' which might do the trick w/o the need of an extension.

**Comment by souldanger** [comment]
Hi John,
here's a temporary solution for the extension issue.
Install the last Iridium Browser version from
- Windows https://downloads.iridiumbrowser.de/windows/2020.01.79/
- macOS https://downloads.iridiumbrowser.de/macos/2020.01-0/
Then install the extensions you like, once done upgrade to latest version.
