### ISSUE TITLE
Install issue: no public key/trying to import a key with a gmail-registered userid 

### ISSUE THREAD

**Issue by Patron77** [iridium-browser/tracker#270]
Hi, 
I was installing the browser on a trial basis and it gives me this warning on a CentOS 7 machine:
---------------
warning: /var/cache/yum/x86_64/7/iridium-browser-project/packages/iridium-browser-2020.04.81-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 0a23ec69: NOKEY
Public key for iridium-browser-2020.04.81-1.el7.x86_64.rpm is not installed
iridium-browser-2020.04.81-1.el7.x86_64.rpm                                                                     |  81 MB  00:00:10     
Retrieving key from https://downloads.iridiumbrowser.de/epel7/pubkey.gpg
Importing GPG key 0x0A23EC69:
 Userid     : "Wasser Mai <wasser19641@gmail.com>"
 Fingerprint: a262 a4cd 64e7 ae7f 00cb e8fd 1783 458b 0a23 ec69
 From       : https://downloads.iridiumbrowser.de/epel7/pubkey.gpg
--------------
1. Is this safe to continue?
2. Who is Wasser Mai? with an address on gmail?
All this seems to me a bit odd.
thank you.

**Comment by souldanger** [comment]
Hi,
yes it is safe!
It is the private gpg key and email of our Fedora and RHEL/CentOS developer.
All rpms also include a srpm to unpack and enable user to build themselves.
