### ISSUE TITLE
2020.04.81 isn't working with the web store

### ISSUE THREAD

**Issue by metapea** [iridium-browser/tracker#271]
When ever i tried to install an extension from the web store, it's mostly repeats with:
1. when clicking on Add to Chrome it goes into [checking](https://i.imgur.com/AyagqOp.png) & does nothing for a long time
2. if you doing anything else like refresh the page or close the browser it bring up [this](https://i.imgur.com/DmbC1mu.png) when you're trying to install the extension for the second time
3. It would lead into A or B:
A. If you close the browser multiple of times you can try to install the extension again but the same thing happen again
B. if you're even lucky it will install but the extension wouldn't or would barely work

**Comment by souldanger** [comment]
Certain extensions wont work due to
- making requests to Google i.e. Google fonts, scripts or plugins
- bad security / privacy
If you don't mind, please let us know what extensions do cause headaches, so that we can try to reproduce.
Thanks!

**Comment by metapea** [comment]
https://chrome.google.com/webstore/detail/1clickvpn-free-vpn-for-ch/fcfhplploccackoneaefokcmbjfbkenj?hl=en-US
The thing is this one worked nomaly with the last version of iridium.

**Comment by metapea** [comment]
sorry, i clicked that by accident

**Comment by souldanger** [comment]
Please see the extensions privacy policy - that explains everything - because
- it collects user data
- spits out cookies
- uses Google Adsense
- zero info on the developer

I am sorry, but this is not a reliable VPN service at all. It seems to me as they are after your information/data and nothing else.
Why not setup your own VPN?

**Comment by metapea** [comment]
> Why not setup your own VPN?

I have to cule on how to that in the first place (also trying to save money), so convenience.
I just prefer the brower, _if you can find a ''no-login open source vpn for chrome''_ i would use that, but there seems to be none sadly.
It's a vpn from a webstore, i knew what i was getting into.
I just wished it still worked & i thought something was wrong with the browser when it wasn't working. 

>I am sorry, but this is not a reliable VPN

Oh well, if it's blocked then add a warning to the blocked extensions next time so i don't have to bother you or be confused.

I will close this in a day or two if it's just that extension that's not working.

**Comment by souldanger** [comment]
We simply cannot flag or mark extensions as we do not control any of these - plus there are zillions out there. The entire process is 'auto-block' by not disclosing user data. So if an extension does not work with Iridium Browser it is probably not safe in the first place.

If you absolutely positively need to use certain software/extensions for whatever reason, all we can recommend is using a second browser for this and Iridium for secure and private use.
Thank you for your understanding!

**Comment by metapea** [comment]
Going to close this, since i've tested with reinstalling some of the other extensions and they seems to be fine.

>We simply cannot flag or mark extensions as we do not control any of these 

Oh, i thought you implying something different altogether for a moment. sorry about that.
