### ISSUE TITLE
home page doesn't load on Windows x86 portable version

### ISSUE THREAD

**Issue by floxblah** [iridium-browser/tracker#273]
I just downloaded the last portable version of iridium (2020.04.81) for Windows x86.
Here's my issue :
When i set a default page and try to open the browser, The url that i set is correct but i have to refresh the page to display the content.

**Comment by souldanger** [comment]
That's correct!
By default, Iridium Browser clears all cookies and website data when you quit the browser.
This can be changed at your own discrection in Settings > Privacy and security > Site settings > Cookies and site data. Then uncheck 'Clear cookies and site data when you quit the browser'.
But this is NOT recommended at all.

**Comment by floxblah** [comment]
> That's correct!
> By default, Iridium Browser clears all cookies and website data when you quit the browser.
> This can be changed at your own discrection in Settings > Privacy and security > Site settings > Cookies and site data. Then uncheck 'Clear cookies and site data when you quit the browser'.
> But this is NOT recommended at all.

I'm sorry to insist but the portable x64 version does not produce the same behaviour described above and the setting 'Clear cookies and site data when you quit the browser' is checked.
Furthermore uncheck this setting in the x86 version does not solve the issue.

**Comment by souldanger** [comment]
Hmm, I have tested on a old 32-bit Win10 machine and it seemed to work fine.
Do you run any extensions?

**Comment by floxblah** [comment]
I don't run any extension. I just downloaded a fresh version of the x86 portable version.
I tried to reset the default settings (even if i didn't change anything) and it fixed the issue. 
Sorry for the inconvenience.

**Comment by souldanger** [comment]
Hi Florian
you probably had the profile of a previous installation of Iridium still on your machine that might have caused the hickup.
If thats the case the user profile of a standard Iridium Browser version can be found at `C:\Users\*USERNAME*\AppData\Local\Iridium`
