### ISSUE TITLE
Browser not being patched frequently enough may lead to security issues

### ISSUE THREAD

**Issue by artemislena** [iridium-browser/tracker#274]
See e.g. https://security.gentoo.org/glsa/202005-13. Chromium, while more secure than Firefox, also has vulnerabilities, which are fixed in later versions, however Iridium is well behind that latest version.

**Comment by souldanger** [comment]
Thank you for your input!
These CVE's do not apply to Iridium due to its privacy/security enhancements.
Both of these services are blocked by default.
