### ISSUE TITLE
How to update extensions, without losing statistic data

### ISSUE THREAD

**Issue by Marek33** [iridium-browser/tracker#276]
I would like to know, how can I manually update the extensions like uBlock Origin, Cookie Auto Delete and Decentraleyes, without losing any statistic data from those extensions. The method, which I used with the uMatrix doesn't work, since then I would lose the data.

**Comment by souldanger** [comment]
Hi Marek
it's relatively simple;
backup your extensions settings before updating and reinsert these once updates have been installed. The settings can be found in Windows at `C:\Users\%user%\AppData\Local\Iridium\User Data\Default\Local Extension Settings`.

**Comment by Marek33** [comment]
@souldanger Thanks! I did use the Sandboxie, to be sure, which files to copy, and it worked nicely!
