### ISSUE TITLE
Unable to disable extensions on Iridium Browser (Windows)

### ISSUE THREAD

**Issue by leonardo73-max** [iridium-browser/tracker#278]
Hello there, I'm having a problem with the latest build of Iridium (I don't know previous builds), I can't disable extensions and I can't even remove them, is there a workaround or you can fix it in the next builds?

**Comment by souldanger** [comment]
Click on the extension icon next to the address bar to access options or to remove any extension.
also see  FAQ @ https://iridiumbrowser.de/faq
