### ISSUE TITLE
DRM content is not playing in Fedora, working in chromium-freeworld

### ISSUE THREAD

**Issue by mattalxndr** [iridium-browser/tracker#279]
I was having issues watching Netflix. The videos were giving me what looked like a DRM error in chromium, iridium, firefox, and vivaldi. When I uninstalled chromium and installed chromium-freeworld, I am now able to watch Netflix in chromium-freeworld, firefox, and vivaldi, but iridium is still giving me the same error:

![](https://i.imgur.com/WaxGTRU.jpg)

```
# cat /etc/redhat-release                                    
Fedora release 31 (Thirty One)
```

```
# dnf list --installed chromium-freeworld iridium-browser vivaldi-stable firefox
chromium-freeworld.x86_64 81.0.4044.138-1.fc31 @rpmfusion-free-updates 
firefox.x86_64 76.0.1-1.fc31 @updates                
iridium-browser.x86_64 2020.04.81-1.fc32 @iridium-browser-project
vivaldi-stable.x86_64 3.0.1874.38-1 @vivaldi                
```

Iridium:

![](https://i.imgur.com/7XKSanA.png)

chromium-freeworld

![](https://i.imgur.com/9JDl9h7.png)

**Comment by mattalexx** [comment]
Iridium:

![](https://i.imgur.com/7XKSanA.png)

chromium-freeworld

![](https://i.imgur.com/9JDl9h7.png)

**Comment by souldanger** [comment]
please refer to the [**FAQ**](https://iridiumbrowser.de/faq#av-players)
