### ISSUE TITLE
Cannot download languages from settings

### ISSUE THREAD

**Issue by ScribbleGhost** [iridium-browser/tracker#280]
In version 20.04 I cannot download languages from settings. It is if something is blocked. I have never blocked anything google in my firewall. This works in version 2020.01 and I am able to do this in Edge (Chromium).

![2020 06 03-09 52 07](https://user-images.githubusercontent.com/49068170/83610698-2b5af680-a580-11ea-801a-b4d40cdc2e61.png)

**Comment by souldanger** [comment]
Thank you for the heads up!
Unfortunately this is a bug we found in the latest release. However, we have addressed the issue and are testing at present - an update will be released in the next couple of days.
In the meantime you can use version 2020.01 available @ 
Windows: https://downloads.iridiumbrowser.de/windows/2020.01.79/
macOS: https://downloads.iridiumbrowser.de/macos/2020.01-0/

**Comment by medozas** [comment]
Fix has been deployed with 2020.04.81.1 which is online now. Thanks for your bugreport!
