### ISSUE TITLE
Windows version / startpage not loading on browser start

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#281]
I updated to Version 2020.04 (Offizieller Build) (64-Bit) on my Windows 10 x64 today. Since the update my startpage (Google.de) does not load anymore. I would have tried if it's fixed by turning off my extensions, but they turn back on automatically and don't stay switched off. Iridium just shows a blank white screen, loading animation and nothing. If I click on the home page button Google loads.

**Comment by souldanger** [comment]
Hello,
by default Iridium Browser loads a blank page on startup.
However, this can be changed to your needs at your own discretion in 3 simple steps;

1. go to settings - 3 dots on top right, then click on 'Settings'
2. click 'On startup' - menu list on the left
3. activate 'Open a specific page or set of pages' and enter the url of the page that should be loaded on startup

That's it!

**Comment by ghost** [comment]
Did you even read my bugreport? Reading your answer I guess no. I did set a startpage, but it does not load anymore after I updated Iridium. And I found now, that if Iridium is closed, and opens a link e.g. from Outlook e-mail the page does not load, too. Seems like however that if Iridium is opened it can't load pages. One has to click on the start/home page button, so one can browser again.

**Comment by ghost** [comment]
Nevermind. I uninstalled Iridium. It's not usable with that bug.

**Comment by souldanger** [comment]
fully up to you....
An update will be released later on today.

**Comment by medozas** [comment]
> Did you even read my bugreport? Reading your answer I guess no. I did set a startpage, but it does not load anymore after I updated Iridium. And I found now, that if Iridium is closed, and opens a link e.g. from Outlook e-mail the page does not load, too. Seems like however that if Iridium is opened it can't load pages. One has to click on the start/home page button, so one can browser again.

Thanks for your bugreport. The bug has been isolated and fix just went online. You can find it as version 2020.04.81.1. Sorry for the overlap in communication, but giving us a few hours to isolate and fix the bug is I think fair, and delivering a fix within 4 hours a reasonable timeframe ;). If you keep on using Iridium enjoy, otherwise still have a nice day. :)

**Comment by ghost** [comment]
> Thanks for your bugreport. The bug has been isolated and fix just went online. You can find it as version 2020.04.81.1.

Wow, you guys are fast. Respect. I just started playing around with SW Iron a lil bit.
Didn't mean to be offensive in any way - Bugs like that are just a PITA if one opens the browser so many times a day. Thanks for the response and your work, folks. I still prefer projects like Iridium and SW Iron somehow. Brave and Vivaldi and those are just so bloated (they are still good though).
