### ISSUE TITLE
Windows version / extensions get switched active again automatically

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#282]
I updated to Version 2020.04 (Offizieller Build) (64-Bit) on my Windows 10 x64 today. Since the update I can not really deactivate my extensions / plugins. I turn them off using the switch in the extension section, close the page or restart the browser to find them switched on again.

**Comment by souldanger** [comment]
Unfortunately the extension panel does not  fully work in Iridium Browser - see [FAQ](https://iridiumbrowser.de/faq) and scroll down to extensions.
If you want to temporarily disable extensions, you'll have to turn them off from the extension itself .
Open the extension by clicking on the extension icon next to the address bar.
This works with most extensions but not all.
