### ISSUE TITLE
Re-open closed tab

### ISSUE THREAD

**Issue by bellgamin** [iridium-browser/tracker#284]
Other browsers allow user to "re-open closed tab" or "undo closed tab". Iridium does not. Please add this capability.

**Comment by SharpOB** [comment]
Ctrl+Shift+T

**Comment by bellgamin** [comment]
Yessss!!!! Thank you to the nth.(^_^)

**Comment by bellgamin** [comment]
My need was very quickly met. Current Iridium version for Windows is 2020.04, just ~ 2 months since issue. It works GREAT! Fast, stable, easy on system resources -- excellent browser!
