### ISSUE TITLE
Why does your policy allow to use outdated (over 1 year old) browser?

### ISSUE THREAD

**Issue by chymian** [iridium-browser/tracker#290]
As I want to come back to use iridum-browser, which I dropped inbetween cause of install/update pbls, I found out that the debian-based browsers are over a year old, compared to the others, which are "only" 3 month old.
how can that happen? does that mean there are no known bugs/issues in version 2019.04 and  Chromium 73.0.3683.103 – which I doubt.

Since the security of a browser is one of the most important sec-issues on a system I'm not sure, what could be the reason for that?

and what is the update policy on iridium? haven't found any info on the website.

TIA for clarification
gruss, günter

**Comment by summersab** [comment]
Hey, @chymian - from https://iridiumbrowser.de/news/2020/02/28/version-2020.01.79 :

> Our Debian/Ubuntu developer has moved on and we are currently looking to fill that position. If you would like to join the development team, check out the source code and if you feel comfortable building Iridium for Debian-based systems, let us know.

**Comment by jengelh** [comment]
It's open-source — use is not restricted.
