### ISSUE TITLE
Adding More Privacy Search Engines

### ISSUE THREAD

**Issue by InfinitySearch** [iridium-browser/tracker#292]
Hello everyone. Since Iridium is a privacy based web browser, it might be worth adding more private search engines into it by default. While it already has DuckDuckGo and Qwant, you could still consider adding StartPage, Mojeek, Us, and others. Here is a complete list of privacy search engines that we made at https://alternativeto.net/list/13568/privacy-search-engines.

**Comment by ivan-paleo** [comment]
I can only agree. 
But StartPage might not be a good choice anymore and I'm not sure about DuckDuckGo either (see https://restoreprivacy.com/private-search-engine/). I can recommend [Swisscows](https://swisscows.com) though.

In general, the problem with privacy search engines is that you would have to update the list fairly regularly. So maybe it's not necessary to add more by default, but it might be better to rather point toward a list of search engines and let the user choose and add the one(s) he/she wants.

**Comment by 29039** [comment]
What is wrong with StartPage? I thought they they just proxy Google results but without the Google tracking

**Comment by 29039** [comment]
And +1 for including StartPage

**Comment by souldanger** [comment]
You can add or remove any search engine that you like at your own discretion.
