### ISSUE TITLE
Can't be opened on MacOS

### ISSUE THREAD

**Issue by 24coding** [iridium-browser/tracker#294]
<img width="532" alt="Screenshot 2020-07-31 at 02 17 48" src="https://user-images.githubusercontent.com/32367942/88987015-df54d580-d2d4-11ea-8f94-23c3135dd0dd.png">

**Comment by kaleidoscopique** [comment]
That's explained on the download page + FAQ :

> Iridium Browser is currently signed but not notarized by Apple. Therefore you will need to update your security settings to allow installing Iridium Browser.
> In “System Preferences”, click “Security & Privacy”, then click “General”.
> Click the “lock” and enter your password to make changes.
> Select “App Store and identified developers” under the header “Allow apps downloaded from”.
> Further details can be found at [Apple support](https://support.apple.com/en-us/HT202491).

**Comment by 24coding** [comment]
It was a bug in MacOS. The normal option to "Open Anyway" appeared after a reboot. I forgot to mention it in the initial issue description, sorry.
