### ISSUE TITLE
Iridium has wrong link to Google sign in

### ISSUE THREAD

**Issue by bellgamin** [iridium-browser/tracker#297]
Under settings for "You and Google," on the line titled "Get Google Smarts in Chrome," the click bar labeled "Turn on Sync" has an incorrect link that yields a 404 Error. That link should be corrected to 
https://accounts.google.com/Login

(The INCORRECT link is https://accounts.google.com/Login/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F )

**Comment by jengelh** [comment]
I could not reproduce it in 2020.11.85 anymore (Google changed the underlying URL); however, it has been disabled anyway in that version so should no longer be a factor.
