### ISSUE TITLE
Problem: nothing provides libicui18n.so.66()(64bit) needed by iridium-browser-2020.04.81-3.5.x86_64

### ISSUE THREAD

**Issue by rsysadmin-com** [iridium-browser/tracker#298]
Hi all,

I got that error message when trying to install Iridium Browser on my OpenSUSE Tumbleweed today.

To reproduce follow the instructions from
https://iridiumbrowser.de/downloads/opensuse

Thanks,

**Comment by souldanger** [comment]
please update to latest version

**Comment by rsysadmin-com** [comment]
This is still happening for the latest version of the Iridium Browser:

rigel:~ # zypper ar https://downloads.iridiumbrowser.de/openSUSE_Tumbleweed/ iridium
Adding repository 'iridium' ..........................................................................................................................................[done]
Repository 'iridium' successfully added

URI         : https://downloads.iridiumbrowser.de/openSUSE_Tumbleweed/
Enabled     : Yes
GPG Check   : Yes
Autorefresh : No
Priority    : 99 (default priority)

Repository priorities are without effect. All enabled repositories share the same priority.
rigel:~ # zypper in iridium-browser

New repository or package signing key received:

  Repository:       iridium
  Key Fingerprint:  A321 E91F 574F DB85 538A F350 ADF2 A64D EAFF FE6C
  Key Name:         NETitwork Development <development@netitwork.net>
  Key Algorithm:    RSA 4096
  Key Created:      Mon Sep 22 14:42:10 2014
  Key Expires:      Thu Sep 19 14:42:10 2024
  Subkey:           E8A3E8D48624E916 2014-09-22 [expires: 2024-09-19]
  Rpm Name:         gpg-pubkey-eafffe6c-54201922



    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: A GPG pubkey is clearly identified by its fingerprint. Do not rely on the key's name. If
    you are not sure whether the presented key is authentic, ask the repository provider or check
    their web site. Many providers maintain a web page showing the fingerprints of the GPG keys they
    are using.

Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): t
Building repository 'iridium' cache ..................................................................................................................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libicui18n.so.70()(64bit)' needed by the to be installed iridium-browser-2021.10.95.1-1.5.x86_64
 Solution 1: do not install iridium-browser-2021.10.95.1-1.5.x86_64
 Solution 2: break iridium-browser-2021.10.95.1-1.5.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):

**Comment by rsysadmin-com** [comment]
Perhaps re-opening this issue would help... :-) 

Thanks!
