### ISSUE TITLE
Pages crash with "Aw, snap!" error persistently

### ISSUE THREAD

**Issue by jarmery** [iridium-browser/tracker#299]
OS: Linux Mint 20
Kernel: 5.4.0-42-generic
DE: Cinnamon
Iridium version: Version 2019.04 (Developer Build) Built on Ubuntu 16.04

Certain pages constantly crash with an "Aw, snap" error while others have no issue loading, so it doesn't appear to be a lack of memory. Terminal outputs the following during the failure:

`../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
Received signal 11 SEGV_MAPERR 0000000000e6
#0 0x560d16bc9239 <unknown>
#1 0x560d16b0b0e3 <unknown>
#2 0x560d16bc8db1 <unknown>
#3 0x7f60bb2c03c0 <unknown>
#4 0x560d17f755f3 <unknown>
#5 0x560d17f7b0c8 <unknown>
#6 0x7f60bb2c03c0 <unknown>
#7 0x7f60b95b3361 clock_nanosleep
#8 0x7f60b95b8eb7 nanosleep
#9 0x560d13f01ca5 <unknown>
#10 0x7f60bb2b4609 start_thread
#11 0x7f60b95f5103 clone
  r8: 0000560d1b781650  r9: 0000000000000006 r10: 0000000000000000 r11: 0000000000000000
 r12: 00007f60b0b33640 r13: 00007f60b0b32240 r14: 00007f60b0b32178 r15: 0000560d1f41ec00
  di: 0000000000000000  si: 00007f60b0b32020  bp: 00007f60b0b32150  bx: 00000000000000e6
  dx: 0000000000000000  ax: 0000000000000000  cx: 00000000000000e6  sp: 00007f60b0b32140
  ip: 0000560d17f755f3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 00000000000000e6
[end of stack trace]
Calling _exit(1). Core file will not be generated.
`

**Comment by jarmery** [comment]
For clarity, I've found this occuring on two pages now.

https://voice.google.com/u/0/signup
https://www.aliexpress.com/

**Comment by dking-after** [comment]
I see the same behavior regularly, as well.

Iridium version: Version 2019.04 (Developer Build) Built on Ubuntu 16.04
Kernel: 5.4.0-7642-generic
Desktop: Mint Cinnamon
OS: Pop!_OS 20.04 64-bit

Another example: https://www.ebay.com/

**Comment by alexkowel** [comment]
Reproducing the issue on Ubuntu 20.10 as well.

**Comment by Flashwalker** [comment]
Confirming this. It affects many sites:  
https://jut.su/  
https://hh.ru/  
`--no-sandbox` option solves.

**Comment by souldanger** [comment]
please update to latest version

**Comment by Flashwalker** [comment]
> please update to latest version

Please release fresh version for Linux
