### ISSUE TITLE
Connecting to Google on startup

### ISSUE THREAD

**Issue by BlockMen** [iridium-browser/tracker#301]
Why is Iridium connecting to a Google server (216.58.213.205, 172.217.23.110, ...) right after installation and startup. No search nor other request performed, just installed and started.

**Comment by GalacticSun** [comment]
See: https://www.clearhat.org/2018/04/18/configuring-iridium-browser-with-even-more-privacy-than-default/

The first screenshot on that page says that Chromium aleady has a tracker installed that phones home when you install it for the first time and to turn off your network when you first install it.  Then set startup pages to blank, make other config changes on that page and any others you want, then re-enable your network.

Not sure why the Iridium guys haven't removed this...?
Has this been removed, Iridium Devs?

**Comment by kilbith** [comment]
Open up the BlockPlanet sources, as$h@le.

**Comment by jengelh** [comment]
```
*** URLRequest(https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard)
```
I presume you mean this request that is visible on the console. It has been located and disabled in version 2020.11.85.
