### ISSUE TITLE
> 24 hour respository outage, again; website not working

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [iridium-browser/tracker#303]
Some six times now - over the course of a year or two - the Iridium repository has begun a protracted malfunction. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/93644368-beb61b80-f9f9-11ea-830e-d081955fcdf9.png)

Also, your website (https://iridiumbrowser.de) seems to be down.

Is it a money problem? [This webpage](https://itsfoss.com/iridium-browser-review/) seems to say you have serious backing.

**Comment by narcisgarcia** [comment]
Website and binaries repository is down.
Ask me if you need infrastructure help.

**Comment by narcisgarcia** [comment]
Website and binaries repository is down.
Ask me if you need infrastructure help.

**Comment by narcisgarcia** [comment]
Website and binaries repository is down.
Ask me if you need infrastructure help.

**Comment by souldanger** [comment]
Server back up - was down for maintenance!

**Comment by LinuxOnTheDesktop** [comment]
> Server backup - was down for maintenance!

Thanks for telling us.

_However_, and as my report said: this happens _periodically_.

I add the following. On Linux, that situation plays merry hell with package upgrades. For, it means that, for the period the problem exists, _every time someone checks for any updates to their system_, there is a delay and eventually an error message that will perturb neophytes. Others run repositories with the help of fewer resources that Iridium seems to have, and yet those other repositories do not generate problems like this. Moreover, these problems have made me think of dropping Iridium. For I begin to think that it is just not worth the hassle.

**Comment by narcisgarcia** [comment]
Project may need mirrors to host repositories.

**Comment by LinuxOnTheDesktop** [comment]
Yesterday the repository went down yet again and I could not access your website or even this GitHub page. I am sorry, but I have had enough: I'm removing Iridium from my computers.

**Comment by narcisgarcia** [comment]
I most complain because of debian based packages are completely outdated, and I install Chromium derivatives at much computers I deploy with GNU/Linux (Debian, Ubuntu, Trisquel and others).

I think this project is necessary, the idea is better than Chromium because it kicks Google from any default behaviour, and some website failures aren't enough reason to prefer another web browser (which one?).
