### ISSUE TITLE
Native Client

### ISSUE THREAD

**Issue by Marek33** [iridium-browser/tracker#304]
I would like to know if you know how to remove the Native Client, since it's not a secure plugin and I don't need it anyway. Since Iridium is considered a private browser, it shouldn't have it anyway.

**Comment by GalacticSun** [comment]
+1
Also curious about this.

**Comment by jengelh** [comment]
`grep enable_nacl README.md`

**Comment by Marek33** [comment]
@jengelh  Sorry, but I don't understand, what does have anything with the Native Client. _Well, since it's no longer in the new version, I guess it was not important then._

**Comment by Marek33** [comment]
@jengelh Why is this re-enabled, in the latest release?
