### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by questionanswertgs** [iridium-browser/tracker#310]
hello there

To avoid rewriting the same identical suggestions, I send you some links. In the last days I published so many new suggestions.

about suggestions, you can find a lot of suggestion
1) my edge suggestions here: https://link.ws/edgesuggestions
2) suggestions I liked from other user here: https://link.ws/othersuggestions (where I added additional suggestion too)
3) my first chromium suggestions list 1: https://link.ws/chrome1 and my second list: https://link.ws/chrome2

Note: From end 2020-10 all suggestions are written on both Edge and Chrome at the same time, suggestions before 2020-10 are available only on Chrome. This mean chrome 1 contains suggestions not available in edge, chrome 2 instead contains both.

Note2: please ignore the batch won’t fix in list 1. They ban me immediately after that and added a batch won’t fix without considering the suggestions at all (just to close quickly the case). As you see in list 2 the problem is not visible, because I use another method to suggest improvements.

I know this is edge/chrome based, but iridium is chromium based too, so you can really get a lot of useful suggestion reading my suggestion. All my new suggestion are written with both edge and chromium link, so you can see both at the same time too (in case you are interested to the opinion of other devs…)

IMPORTANT:

i hope you will avoid to implement chrome://flags/#extensions-toolbar-menu remotion at all (so you need to keep such option like i wrote https://bugs.chromium.org/p/chromium/issues/detail?id=1124878&hotlist_id=9983&sort=%20rank%20-ID or https://old.reddit.com/r/chrome/comments/jd14kw/suggestions_backup_all_chrome_based_browser/ or other)

**Comment by jengelh** [comment]
We share the same reasons as the other respondents on Technet and chose not to implement any of the requests.
