### ISSUE TITLE
is it safe against tracking?

### ISSUE THREAD

**Issue by lsalamon** [iridium-browser/tracker#313]
I run test page at https://panopticlick.eff.org and result is bad.

Will this be improved?

**Comment by jengelh** [comment]
I don't know what your idea of "bad" is.

>Is your browser blocking tracking ads?

As a user you can install ublock origin.

>Does your browser unblock 3rd parties that promise to honor Do Not Track?

Promises are worth nothing these days, so there will be no effort made to change the behavior.

>Does your browser protect from fingerprinting?

As a user you can disable Javascript to convey fewer information.
