### ISSUE TITLE
"Your browser is managed."

### ISSUE THREAD

**Issue by igh2** [iridium-browser/tracker#314]
I'm using the fedora 33 packaged 2020-4 version.  The "About Iridium" page states my browser is managed.

By whom, and what capabilities are managed?

I also notice the calls home to Google have not yet  been disabled.  Shouldn't this be a priority, for a privacy/transparency focused browser project?

**Comment by souldanger** [comment]
It says that, because some code is ammended with 'user policies'. 
Most calls home are deactivated, even though some, we think are useful are still there i.e. safebrowsing, etc.
However, no user data is being transferred.
