### ISSUE TITLE
Loading traced URL

### ISSUE THREAD

**Issue by gauntlet7649** [iridium-browser/tracker#316]
I keep getting this when i search something on google and before the https on address bar theres trk:113 before it
[https://s8.gifyu.com/images/Capturebb2fc51b5776257a.png](url)
[https://s8.gifyu.com/images/Capture2dac2c311805c1ab4.png](url)

how do i turn this off or is this a bug?

**Comment by orelphevans** [comment]
I get this too, it is very annoying. Also google search suggestions do not seem to work in the address bar, even when enabled in the settings.

**Comment by souldanger** [comment]
Hi guys
the 'loading traced url' bar will no longer appear in the new version 2021-03.
Source code as well as a build for openSUSE is available already. Builds for Windows, macOS, Fedora and RHEL to folow soon.

**Comment by pm-pm** [comment]
Hello,
what is "soon"? Today, 24.6.2021 i can not find an updated windows version. (Still 2020.11.85)
Please announce the release date. :-)
Thanks.

**Comment by spinalgr1990** [comment]
I have the same problem

**Loadind traced URL: trk:113**

![traced](https://user-images.githubusercontent.com/63348163/196028642-cff3206d-cfa5-48fc-9156-b6a786afdea8.png)
