### ISSUE TITLE
Lastpass Vallet message popup

### ISSUE THREAD

**Issue by johbru0** [iridium-browser/tracker#318]
Anyone else getting a **popup message when loading the vault in Iridium**? I am using Google Iridium browser 2020.04.81.1-x64 (6/3/20). The popup does not react or disappear despite clicking "got it" at the bottom of the message. **This prevents me from being able to see the vault**.  out of curiosity i loaded Lasspass in other browsers to see if it could be closed out and it did Firefox and Chrome and Vivaldi. It seems to be an Iridium-only problem. This is using Iridium on my desktop which is where i normally use it. Please help with a solution. Below is the screenshot...

![Lastpass Vault message](https://user-images.githubusercontent.com/65101912/103161455-ce7e9200-4796-11eb-98b2-bef7a751db18.png)

**Comment by souldanger** [comment]
Hi
can't seem to reproduce this behaviour.
Please update to latest version and let us know if this solves the issue.
Thanks!

**Comment by johbru0** [comment]
Michael, i'm already using your latest version. What i described happed for 2 days and then it disappeared. Now i see the lastpass vault clearly w/o the interference blackage at all. Guess its resolved but thaqnk you for getting back to me.

John Brush

December 29, 2020 10:38:36 AM CET "Michael Suldinger " <> wrote:

     Preview: Hi can't seem to reproduce this behaviour. Please update to l --> SPAM? CLICK to BLOCK    

This email is Masked using Blur - it was sent from github.com to 7thbxpgmeggp@opayq.net (your reply stays Masked). To protect your privacy, do not forward this message, or add new recipients like CCs or BCCs.    

Thanks for being a Blur customer! If you haven't yet, [ Try DeleteMe at a discount. ]  

Hi
can't seem to reproduce this behaviour.
Please update to latest version and let us know if this solves the issue.
Thanks!
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/iridium-browser/tracker/issues/318#issuecomment-752012927","url": "https://github.com/iridium-browser/tracker/issues/318#issuecomment-752012927","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

-- 
Sent with https://mailfence.com
Secure and private email
