### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by skeeper1** [iridium-browser/tracker#320]
Hi, I'm using Versión 2020.11 (Build official) (64 bits) of Iridium on Windows 8.1

I'm not able to delete the chrome extensions I have installed.

The mouse simply do not work on the on/off button or on the delete extension option

Any suggestions? Thanks.

**Comment by mlunax** [comment]
Why you closed this?
I have a similar problem, in Iridium gui I can delete extention only via mini Extensions bar(pic num 1 below)
![image](https://user-images.githubusercontent.com/11018865/105003021-6d16af80-5a32-11eb-93db-fab3d505c680.png)

I can delete extension via local files ofc too.

**Comment by souldanger** [comment]
Hi,
please check out our FAQ @ https://iridiumbrowser.de/faq#access-extension
Thanks!

**Comment by Flashwalker** [comment]
And how can i delete extension that has no icon?

**Comment by mlunax** [comment]
> And how can i delete extension that has no icon?

Delete in files of the browser.
