### ISSUE TITLE
Unable to change default search engine

### ISSUE THREAD

**Issue by ivan-paleo** [iridium-browser/tracker#322]
I have just installed Iridium and I've cleaned up some of the pre-installed search engines. I would like to use Swisscows or metaGer by default, but it seems I cannot replace Qwant as the default (see screenshot).

![Capture](https://user-images.githubusercontent.com/12525997/106748411-1c4fab00-661d-11eb-9566-11d05f124a5e.PNG)

Is it wanted or is that a bug?

I am working on Windows 10 with Iridium Version 2020.11 (Official Build) (64-bit)

**Comment by souldanger** [comment]
This should be solved in the current release - please download from https://iridiumbrowser.de/downloads/

**Comment by ivan-paleo** [comment]
Indeed, thanks!
