### ISSUE TITLE
Iridium Version 2020.11 Crashing

### ISSUE THREAD

**Issue by tenpoundhero** [iridium-browser/tracker#323]
I'm on Mac OS 11.2 with Iridium Version 2020.11 and am occasionally getting crashes with GUI glitches in the browser window as seen in the attached screen shot.
<img width="1273" alt="Screen Shot 2021-02-04 at 9 49 16 PM" src="https://user-images.githubusercontent.com/33327034/106983990-c8d08080-6734-11eb-896e-dbe0e0f7ac68.png">

**Comment by souldanger** [comment]
please get the latest build from https://iridiumbrowser.de/downloads/macos
