### ISSUE TITLE
chrome://extensions/ Broken

### ISSUE THREAD

**Issue by cramik** [iridium-browser/tracker#327]
I found like a 3 year old post on the same thing. Bug is not fixed, using most recent portable Windows binary. Can't enable, disable, or remove extensions via chrome://extensions/.

**Comment by cramik** [comment]
semi-fresh download btw. I installed 4 extensions: Augmented Steam, Bitwarden, Dark New Tab (disabled, cant reenable), and OneTab + disabled SafeSearch in settings.

**Comment by fpicchi** [comment]
https://iridiumbrowser.de/faq

>**Why do extensions not update automatically and why does the extension panel not fully work?**  
Updating the extensions automatically does not work, as it would require a connection to the Chrome Web Store. This is also the reason why the extensions panel at **chrome://extensions does not fully work — disabling/enabling (check box) and removing (trash can) will not work.** Also, all extensions will show a ‘Not from Chrome Web Store’ note, even if downloaded from there.
Update any extensions manually by downloading and installing the latest version. Click on the extension icon next to the address bar to access options or to remove any extension.  
You may want to backup your extensions settings before updating and reinsert these once updates have been installed. The settings can be found in Windows at C:\Users\%user%\AppData\Local\Iridium\User Data\Default\Local Extension Settings.

>**How to access or remove an extension from the browser?**  
In Iridium Browser the extension panel does not fully work, therefore you will need to (right-)click the extension icon next to the address bar. This will get you access to all options and to remove an extension by clicking on ‘Remove from browser’.

**Comment by StefanGubler** [comment]
Yes, that's really ODD!  I was searching in the internet and found also posts from 2017. 4 Years ago !
I'm really a fan of the iridium browser, but please keep the software updated, otherwise it will no more be used!

I don't need the "automatic update" function of the plugins, but plugins must be enabled or disabled.
Otherwise we need to have tow browsers, one with activated plugins, one with disactivated plugins.

**Comment by souldanger** [comment]
Please refer to the [FAQ](https://iridiumbrowser.de/faq) to find out how Iridium Browser handles extensions.
There is no bug - we just block a constant exchange with the webstore for good reasons.
