### ISSUE TITLE
FAQ Suggestion - Update Extension Installation FAQ to Include Chromium Webstore as "easy installation" approach

### ISSUE THREAD

**Issue by clawsl** [iridium-browser/tracker#334]
Hi,
I've successfully used [Chromium Webstore](https://github.com/NeverDecaf/chromium-web-store) to easily install several extensions for Iridium (as well as for Ungoogled Chromium). 

That made me wonder if it might perhaps be useful to mention it as potential alternative in the "Extensions" section of your FAQ.

Initially, I had problems dropping it directly onto the extension page. Therefore, I had to enable developer mode first, then refresh the extensions page and after that dropping the crx from Github worked fine for me. After that, developer mode can be disabled again.

Once installed, A user can directly go to the Chrome Webstore and search for an extension. Then click the "Add To Chrome" button for the chosen extension and confirming the installation should work as expected (as long as there is no other conflict like you mentioned in your FAQ)

**Comment by souldanger** [comment]
Hello
we actually block the webstore intentionally as we block most of all connections with Google.
Thank you for your understanding!
