### ISSUE TITLE
offline spell check dictionary

### ISSUE THREAD

**Issue by 10user01** [iridium-browser/tracker#335]
I have a PC which is used for a specific application and cannot be connected to the internet. I recently installed chrome on the PC using an offline installer. However, the installer did not install the spell check dictionary. Chrome is used by the application on the PC and spell check is required. Can anyone point me to an offline installer which also installs the spell check dictionary? Or is there any other way I can get the spell check working without putting this machine on the internet?

**Comment by souldanger** [comment]
we do not build spell checking plugins and do not know of such a offline plugin available.
