### ISSUE TITLE
Native support for Apple's M1 ARM architecture

### ISSUE THREAD

**Issue by franktopel** [iridium-browser/tracker#337]
Brave and Vivaldi already are optimized for Apple's M1 silicon. Is this being considered for Iridium as well?

**Comment by jengelh** [comment]
What makes you believe that Brave has anything M1-specific that is not already part of Chromium?

**Comment by scgf** [comment]
OK. Why not just have a Windows binary and run it using WINE on other platforms? Would you be happy with that?
