### ISSUE TITLE
Any plans on supporting Debian based systems again?

### ISSUE THREAD

**Issue by joshuamzm** [iridium-browser/tracker#338]
A few days ago, my package manager failed because it couldn't sync with the Iridium APT source. I see there are no releases in the `https://downloads.iridiumbrowser.de` so I needed to disable the source.

Are there any plans to get APT support back online?

**Comment by thor171** [comment]
I was wondering the same. Did you drop the support for Debian?

**Comment by narcisgarcia** [comment]
Please, publish step-by-step procedure to buid a Debian package of Iridium browser.

**Comment by aknisly** [comment]
I, too, am interested in a Debian build. I'm glad to see the project is alive; I was starting to worry that it might have died.

**Comment by NIXKnight** [comment]
Lately started having issues with Debian packages:
```
E: The repository 'https://downloads.iridiumbrowser.de/deb/ stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Has Debian support been removed?

**Comment by souldanger** [comment]
Hi all,
we stopped supporting Debian builds for now as the last build was outdated.
It was from April 2019, based on Chromium 73.0.3683.103, which has quite a few CVE's, therefore declared it unsafe and took it offline.
We will continue building for Debain-based systems once we have found a Debian developer.
Please stand by.

**Comment by narcisgarcia** [comment]
Did that old builds reguire a Debian developer?

I succeed on converting RPM package to DEB with this command:
`sudo alien --to-deb --scripts iridium-browser-2021.06.91-1.el7.x86_64.rpm`
(but I'm sure it's better to build from source code)

Could you share the step-by-step recipe was used to buid that old 2019 package?

**Comment by Xanatos00** [comment]
> Did that old builds reguire a Debian developer?
> 
> I succeed on converting RPM package to DEB with this command:
> `sudo alien --to-deb --scripts iridium-browser-2021.06.91-1.el7.x86_64.rpm`
> (but I'm sure it's better to build from source code)
> 
> Could you share the step-by-step recipe was used to buid that old 2019 package?

Thanks, I tried it, but;

`/usr/lib64/iridium-browser/iridium-browser: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory`

I tried many symbolic link for libevent, with no result

**Comment by narcisgarcia** [comment]
I was working with Debian 10 to convert RPM to DEB, and did succeed with iridium 2021.06
I've tried now with Debian 11 same task but:
```
$ sudo alien --to-deb --scripts iridium-browser-2021.10.95-1.el8.x86_64.rpm
$ sudo dpkg -i iridium-browser_2021.10.95-2_amd64.deb
$ iridium-browser
/usr/lib64/iridium-browser/iridium-browser: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libevent-2.1.so.7 /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
$ iridium-browser
/usr/lib64/iridium-browser/iridium-browser: error while loading shared libraries: libwebp.so.7: cannot open shared object file: No such file or directory
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libwebp.so.6 /usr/lib/x86_64-linux-gnu/libwebp.so.7
$ iridium-browser
/usr/lib64/iridium-browser/iridium-browser: error while loading shared libraries: libre2.so.0: cannot open shared object file: No such file or directory
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libre2.so.9 /usr/lib/x86_64-linux-gnu/libre2.so.0
$ iridium-browser 
/usr/lib64/iridium-browser/iridium-browser: symbol lookup error: /usr/lib64/iridium-browser/iridium-browser: undefined symbol: _ZN3re23RE23Arg12parse_ushortEPKcmPv

```
I don't know what to do now.
