### ISSUE TITLE
"certificate has expired" for openSUSE Leap 15.2

### ISSUE THREAD

**Issue by thomasmerz** [iridium-browser/tracker#340]
How does it come? 😞 

openSUSE Leap 15.2 is still supported from SUSE until end of 2021. So there's no (good) reason not to maintain Iridium for openSUSE 15.2 not any more.

![image](https://user-images.githubusercontent.com/18568381/127764308-39d78ecd-102c-4231-b49f-1d7c5ed17403.png)

```
10:12 $ sudo zypper up
Problem retrieving files from 'iridium'.
Download (curl) error for 'https://downloads.iridiumbrowser.de/openSUSE_Leap_15.2/repodata/repomd.xml':
Error code: Curl error 60
Error message: SSL certificate problem: certificate has expired
```

**Comment by souldanger** [comment]
Thanks Thomas!
the certificate issue has been solved.
