### ISSUE TITLE
iridium browser has viruses and malware ?

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#341]
i am shocked to see that a browser which focuses on privacy has malware ! please remove these viruses and malware As soon as possible . here are the results of the portable file in virustotal - https://www.virustotal.com/gui/file/53ac2263d8c7c3b62c01c784636d436ca282b82ec60469b1a4c9419d2bcaee4c/detection

**Comment by souldanger** [comment]
Hello,
there seems to be a 'false positive' with your virus tool.
All our releases are checked on the highest possible levels and therefore never contain any viruses or malware.
