### ISSUE TITLE
Weird version choice

### ISSUE THREAD

**Issue by Marek33** [iridium-browser/tracker#346]
The latest version is apparently based on the Chromium 95.0.4638.69, but on most sites, it says that it's just the Chrome/92.0.0.0, which is very weird. The main problem with this, is that we have no idea, if the Iridium, have all the fixes and especially security patches, up to 95.0.4638.69 or only the ones, up to the Chromium 92.

This site, seems to be one of the best, when it comes to detecting, the exact user agent, since it can easily detect, the majority of user-agent fiddling: https://webbrowsertools.com/useragent/

**Comment by souldanger** [comment]
please update to the latest version
