### ISSUE TITLE
miss Iridium link to webside

### ISSUE THREAD

**Issue by leminsc8er** [iridium-browser/tracker#349]
i cant find the link to [https://iridiumbrowser.de/](https://iridiumbrowser.de/). Pleas Add this next by https://www.chromium.org/ code.

if i go to 

Menü > 
"About Iridium" >
"Iridium
Copyright 2021 browser authors.
The browser is made possible by the [Iridium](https://www.chromium.org/) open source project and other open source software."

**Comment by souldanger** [comment]
Thanks for pointing this out!
we will try to update in future releases.
