### ISSUE TITLE
I can't delete extensions 

### ISSUE THREAD

**Issue by dotcoma** [iridium-browser/tracker#350]
Hi,

I installed 6 extensions -- Bitwarden, Decentraleyes, DuckDuckGo Privacy Essentials, Markdown New Tab, Privacy Badger and Ublock Origin -- and now I simply cannot uninstall any of them. 

Is this a know issue? Is a fix in the works? Thanks.

Massimo

**Comment by souldanger** [comment]
Hi,
please find answers to your questions in the **[FAQ](https://iridiumbrowser.de/faq#extensions)**.
Thanks!
