### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Raj2032** [iridium-browser/tracker#351]
Hey guys, I have some questions regarding this browser:
1. How does it differ to `ungoogled-chromium`?
2. Does Iridium strip off all Google services/APIs?
3. Does the browser still get updates?
4. How do I port my cookies and everything from brave to iridium?

**Comment by souldanger** [comment]
some answers to your questions
1. the exact differences are not known to us - we never compared both.
2. most of all
3. Yes
4. please refer to Chromium migration
