### ISSUE TITLE
Unable to enable/disable extensions on Version 2021.12

### ISSUE THREAD

**Issue by Keitaro32** [iridium-browser/tracker#352]
Hi

I use Version 2021.12 (Build officiel) (64 bits) but the problem still here :-(
No icon of the extension on the the extension manager on the top right, I can not remove in that way...

Probem was here on version 58.0 (look at the post (Unable to enable/disable extensions on version 58.0! #146 )
I do also the @souldanger solution but as say @Flashwalker it still persists on browser extensions page. :-(

When will this bug fix ?

**Comment by souldanger** [comment]
Hi,
the only other solution is deleting the extension in your file manager.
In Windows go to: ```C:\Users\_NAME_\AppData\Local\Iridium\User Data\Default\Extensions```
Then find the extension you would like to delete.

Iridium intentionally blocks connections to the Chrome Web Store for privacy reasons. The unwanted side effect is that extensions don't get updated automatically and the extension panel does not fully work.
Unfortunately there is no other way to make the extension panel work without having a constant connection to the Chrome Web Store, which may transfer other data as well.

Hope this will help!
