### ISSUE TITLE
DuckDuckGo is listed twice by default

### ISSUE THREAD

**Issue by 29039** [iridium-browser/tracker#353]
I got: Qwant, DuckDuckGo, Google, Bing, Yahoo!7, DuckDuckGo, Ecosia by default on a new install of the Portable version.

Version 2021.12 (Official Build) (64-bit)

**Comment by souldanger** [comment]
You can add or remove any search engine that you like at your own discretion

**Comment by 29039** [comment]
Jebus. It's like you're not even interested in making this a good browser
