### ISSUE TITLE
native macos M1

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#357]
Are there any plans to provide a Universal app or even native Apple Silicon app?

**Comment by souldanger** [comment]
There are no plans of building a Apple Silicon compatible app at this stage.
We will post on our website in case that changes.
Thanks

**Comment by ghost** [comment]
Can I compile it?

**Comment by souldanger** [comment]
sure - source code is available - see https://iridiumbrowser.de/downloads/source
