### ISSUE TITLE
Missing Hardware Media Key Handling 

### ISSUE THREAD

**Issue by Nuczzy** [iridium-browser/tracker#361]
Hey there, i don't know if this is intendeed or not but iridium is missing the key hanndling flag so you can't use extensions like the streamkeys one to use global hotkeys for music players, is there a way to bring it back ? i'll try to enabled the 2019 flag and 2020 but it doesn't seem to do anything with it.

Thank you for the aweasome browser tho!

**Comment by jengelh** [comment]
We did not explicitly/willingly turn these off, so maybe that's a change in Chromium itself. Then again, the zoomin and zoomout multimedia keys from a Dell KB522 work just fine in 108.
