### ISSUE TITLE
All Extension On & Off Buttons are Frozen on Iridium Browser

### ISSUE THREAD

**Issue by Lopezzzzzzz** [iridium-browser/tracker#364]
NoteIt Extension was not working in Iridium (NoteIt works fine in all of my over 7 chrome based browsers).     I refreshed page & i exited  Iridium browser.    Iridium browser was opened again.    NoteIt still did not work.    I attempted to shut off NoteIt (where all of Iridium extension settings are); but, the blue dot switch would not move.     5 other extensions could not be turned on or off too.     I could not delete NoteIt extension (within the large page list of Extensions via "More Tools" to get to extension list).     So i clicked on the extension icon to the right of the address bar & i successfully removed NoteIt extension via the small window.     However,  all the extension on & off buttons are frozen in place & cannot be moved.     All of my other many chromium based browsers have never had this problem.    Iridium,  please fix this extension problem.     2nd problem to fix might be why did not NoteIt work in your browser, when it works most of the time in other chromium based browsers.      Iridium,  please fix this 2nd problem if it's caused by you.     I like your browser.     It is much better than a # of other browsers out there.   Thank you kindly.

**Comment by souldanger** [comment]
Hello
please see the [FAQ](https://iridiumbrowser.de/faq) about problems with some extensions and how to remove extensions.
1.) How to access or remove an extension from the browser?
2.) Why do certain extensions do not work in Iridium Browser?
Hope this helps and explains your issues.
Thanks
