### ISSUE TITLE
No "scrollable-tabstrip" flag

### ISSUE THREAD

**Issue by jabberwockxeno** [iridium-browser/tracker#365]
Other chromium browsers have a "scrollable-tabstrip" flag, and related flags, that allow you to use the mouse wheel to scroll through your open tabs once you have the maximum displayable amount open and new tabs would otherwise load out of frame and be inaccessible.

Iridum is sort of unusable to me as a browser without that functionality (ideally which would be one of the more recent versions of the flag where you can also set a minimum tab width, even moreso if we can define it in pixels vs Chromium's preset 3 options).

**Comment by jengelh** [comment]
chrome://flags has #scrollable-tabstrips in 108.
