### ISSUE TITLE
Why are there no repos for openSUSE or SLES 15.4?

### ISSUE THREAD

**Issue by thomasmerz** [iridium-browser/tracker#368]
openSUSE and SLES 15.4 are GA since a while, but there are still no repos for them on https://downloads.iridiumbrowser.de/

![image](https://user-images.githubusercontent.com/18568381/201024343-9a6644e1-151d-49d5-84c7-4327710be92a.png)

Why? 😞

**Comment by jengelh** [comment]
It's all open source and you are free to make these on your own.

(Resolved for 108.)

**Comment by thomasmerz** [comment]
Thanks, that looks great now 😄 

<img width="527" alt="image" src="https://user-images.githubusercontent.com/18568381/205984018-7d9aa9eb-d828-4d51-8023-49ffea9002e2.png">
