### ISSUE TITLE
Windows version way behind

### ISSUE THREAD

**Issue by teknowledgist** [iridium-browser/tracker#370]
I appreciate all the work on this project/product.  

The Windows version is based on Chromium v100 which came out almost a year ago.  Is there going to be a more current release at some point, or is Iridium pretty much aiming for Linux systems going forward?

Thanks.

**Comment by radorn** [comment]
I hope it doesn't take too much longer for a new windows build to be available.

**Comment by radorn** [comment]
It sure is taking long now... is it coming out at all or do I switch to another browser? It'd be a pity if I had to do that.

**Comment by ruwansweb** [comment]
the best memory management browser i used . need an update to the windows version . why is windows version abandoned ?

**Comment by radorn** [comment]
Is it still coming or has Windows support been dropped?

**Comment by souldanger** [comment]
Disgracefully, our Windows and macOS developer is currently not available.

**Comment by ioc2e3** [comment]
> ... , or is Iridium pretty much aiming for Linux systems going forward?

This sentence reminds me of Falkon Browser ( The Windows version is no longer updated ) ...

.

**Comment by ioc2e3** [comment]
> Is it still coming or has Windows support been dropped?

Several updates have no Windows version ...

.
