### ISSUE TITLE
Fedora 36 update conflict with Chromium

### ISSUE THREAD

**Issue by AbuMubarak1378** [iridium-browser/tracker#371]
The following is the output from updating my iridium on Fedora 36

`dnf install iridium-browser -y
Last metadata expiration check: 1:06:47 ago on Wed 01 Feb 2023 01:05:11 PM EST.
Dependencies resolved.
================================================================================
 Package          Arch    Version                Repository                Size
================================================================================
Installing:
 iridium-browser  x86_64  2023.01.109-1.fc36     iridium-browser-project   85 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 85 M
Installed size: 263 M
Downloading Packages:
iridium-browser-2023.01.109-1.fc36.x86_64.rpm 1.6 MB/s |  85 MB     00:53    T------------------------------------------------------------------------------
Total                                         1.6 MB/s |  85 MB     00:53     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/d7/f6ec067eda9866eb43621a2e7448d291c13c48 from install of iridium-browser-2023.01.109-1.fc36.x86_64 conflicts with file from package chromium-common-109.0.5414.119-1.fc36.x86_64
  file /usr/lib/.build-id/0d/0c14a6385046118a777c608a8c98c3cc6269fd from install of iridium-browser-2023.01.109-1.fc36.x86_64 conflicts with file from package chromium-109.0.5414.119-1.fc36.x86_64`

**Comment by wasser19641** [comment]
it looks like chromium and iridium-browser build have same build-id. I fixed this issue in  iridium-browser-2023.01.109-2.fc36. New update will be available in next days.

**Comment by wasser19641** [comment]
iridium-browser-2023.01.109-2.fc36 is now available for update.

**Comment by souldanger** [comment]
fixed
