### ISSUE TITLE
iridium for windows 

### ISSUE THREAD

**Issue by uluturkpro** [iridium-browser/tracker#374]
hi when wil new update release for iridium for windows

**Comment by souldanger** [comment]
> hi when wil new update release for iridium for windows

Hello,
we are currently waiting for validation. Once validated v2023.04 for Windows desktop and portable will be released.
Please stand-by. It shouldn't take long now.

**Comment by radorn** [comment]
I'm guessing it won't be compatible with Windows 7.
Any chance I am wrong?
