### ISSUE TITLE
1Password extension not compatible

### ISSUE THREAD

**Issue by ricsteinberger** [iridium-browser/tracker#376]
Please tweak the Iridium Browser so that the critically important extension 1Password can be easily installed. As of 01 July 2023, this extension is not compatible.  Iridium 2022.04

**Comment by souldanger** [comment]
> Please tweak the Iridium Browser so that the critically important extension 1Password can be easily installed. As of 01 July 2023, this extension is not compatible. Iridium 2022.04

Please ask the 1Password developers to not share data, so it works with privacy focused browsers.
Other password managers, such as Lastpass in example, work like a charm with Iridium Browser.

**Comment by ricsteinberger** [comment]
That's a pretty hostile response. 1Password works with almost very other browser. It should be up to end users whether they want to install/trust this extension.  Please rethink your response -> Allowing 1Password to be installed in Iridium means I will use Iridium. Refusing to allow it means I won't.  If you want to turn away users, then ignore this message.

**Comment by souldanger** [comment]
Dear @ricsteinberger 
we do not disallow or ban certain extensions - I mean there are a gazillion of extensions out there - so how should we, with a small team of 4-5 people, be picking certain extensions that we block?
Iridium Browser is privacy focused, which means certain connections to i.e. Google and other third parties are blocked by default. This means if users choose to use software, that is not privacy focused, these extensions won't work with Iridium Browser.
Again, we are a small team, that does all the work for free, without any donations or sponsorship and simply don't have the time to investigate any and all extensions, as all of us have a job and family.
Therefore we have no other choice, than saying certain extensions do not work with Iridium, which is also laid out in our [FAQ](https://iridiumbrowser.de/faq) on our website.
Thank you for your understanding.
