### ISSUE TITLE
What happened to iridium 2023.06 based on chromium 109 for windows 7, 8 and 9?

### ISSUE THREAD

**Issue by jd-ve** [iridium-browser/tracker#380]
I have noticed that all independent web browsers have updated to version 109 of chromium which is compatible with windows 7,8 and 9; since, iridium did not think about its users; rather, it excludes those who have Windows with versions prior to 10, it should include them all.

**Comment by souldanger** [comment]
You are free to use any older version of Iridium Browser which can be found in the build archive on the download page.
However, please be aware that prior builds to v116 will have CVEs, just like Windows 7 and 8.
For your information: Microsoft never released a Windows 9....
