### ISSUE TITLE
10 major versions behind Chrome?

### ISSUE THREAD

**Issue by mindplay-dk** [iridium-browser/tracker#389]
Is this browser still maintained?

It looks like the last commit was 6 months ago, and going by the version number in the about dialog, it is lacking 10 major releases behind Chrome, is that correct? My concern is, are we missing out on security and quality updates from the main project?

**Comment by rnagy** [comment]
Hi

Yes, but it is being moved off of github. The website and https://git.iridiumbrowser.de/ has the latest code available.

**Comment by ioc2e3** [comment]
> ... , but it is being moved off of github. The website and https://git.iridiumbrowser.de/ has the latest code available.

Excuse me ...

Not everyone knows how to ( build a program from source code ) ...

.

**Comment by mindplay-dk** [comment]
@ioc2e3 I'm not sure this project is really alive - they haven't merged anything to their release branch in over a year, and the download link on the home page doesn't even work.

Try [Thorium](https://thorium.rocks/) instead - it's a humble one-man effort, but at least he releases. 🙂

**Comment by ioc2e3** [comment]
> 試試[Thorium](https://thorium.rocks/)吧——雖然這只是一個人的拙作，但至少他成功了。 🙂

That ...

Here ( https://github.com/Alex313031/thorium/releases ) ...

Is the file with ( .zip ) at the end of the file name a portable version ?

.
