### ISSUE TITLE
Disable new avatar menu

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/tracker#41]
Chromium 44 brings a new feature called "Avatar Menu". Iridium 44 has inherited this, including the request to trk:271:https://www.gstatic.com/chrome/profile_avatars/NothingToDownload which now loads on every start.

Iridium should set the `--disable-new-avatar-menu` parameter by default.

As a workaround until Iridium has this disabled automatically, you can add this parameter when starting Iridium.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-August/000491.html

**Comment by X-Ryl669** [comment]
Yes please do that. I'm moving away from Chrome for this exact reason. Seeing the large amount of person interested in Chrome's bug report item, and the fact that Iridium is the "expressed" solution in that thread, if you make this a default, you're going to get a lot of people using your browser.

**Comment by longsleep** [comment]
Avatar menu is disabled with Iridium 41.1.

**Comment by Huntereb** [comment]
"--disable-new-avatar-menu" has broken on every Chromium distribution with the 4.7 update. I'd love to see it's functionality enforceable... Again. Thank you!

**Comment by jengelh** [comment]
Fixed in version 2020.11.85.
