### ISSUE TITLE
Iridium in fedora? 

### ISSUE THREAD

**Issue by Rat-S** [iridium-browser/tracker#57]
I think Iridium is not available in Fedora official repo.
Please consider adding the package to fedora repo or RPM fusion free repo. 

Is anyone maintaining a [COPR](https://copr.fedoraproject.org/)?

**Comment by jengelh** [comment]
At this time, there are no plans from our side to get the software shipped in distributions. The IR project provides a source tarball and premade builds for selected platforms only.
The task of inclusion into the various distributions is delegated to — that is to say, left for — contributors much more familiar with the particular distributions (and their packaging policies and build systems) to take on, as it frequently happens with free software. This way, the software already found its way into, for example, OpenBSD ports.

**Comment by scottlinux** [comment]
Appears a Fedora package is now available?

http://lists.inai.de/pipermail/iridium/2016-April/000558.html

**Comment by alunux** [comment]
Now, Iridium for Fedora is available in https://dl.iridiumbrowser.de, but it's still using old repo link. The correct repo file is:
```
[f25-iridium-browser]
name=Copr repo for iridium-browser (built by than)
baseurl=https://dl.iridiumbrowser.de/fedora_$releasever/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://dl.iridiumbrowser.de/fedora_$releasever/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```
@jengelh Can anyone update the repo link in https://dl.iridiumbrowser.de/fedora_25/iridium-browser.repo file?

**Comment by alunux** [comment]
Failed upgrade to latest version:
```
[MIRROR] iridium-browser-57.0-2.fc25.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 66502656 but expected size is: 180365026
[FAILED] iridium-browser-57.0-2.fc25.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
Error: Error downloading packages:
  Cannot download iridium-browser-57.0-2.fc25.x86_64.rpm: All mirrors were tried
```

**Comment by ngothan** [comment]
tthe iridium-browser-57.0-2.fc25.x86_64.rpm is corrupt on the https://dl.iridiumbrowser.de/fedora_25/
i have asked Michael to update the file again.

**Comment by souldanger** [comment]
Thanks for letting us know!
Server admin will fix asap.

**Comment by longsleep** [comment]
Iridium now has a Fedora repository. See https://iridiumbrowser.de/downloads/linux.html
