### ISSUE TITLE
Chromium App Launcher does not open & Apps are not shown in the Dock

### ISSUE THREAD

**Issue by KingREADY** [iridium-browser/tracker#60]
Hi,

after installing a Chrome App downloaded from the Google Web Store at my MacBook (OS X El Capitan 10.11.3) I've experienced two problems:
- When I try to open the Chromium App Launcher (at ~/Applications/Chromium-Apps/Chromium App Launcher.app) there does not happen anything. Neither Iridium opens (provided that it's closed before) nor I can see the App Launcher window.
- When I try to open an installed Chrome App I cannot see the app's icon in my Dock. The corresponding app opens and I can use it perfectly fine but with Google Chrome or Chromium each Chrome App gets it's own icon in the Dock - which does not happen when I use Iridium. Instead of this I see a window "Default [random string] has quited unexpectedly". I've pasted the stack trace here: http://pastie.org/private/dsfjnb95id9jva6kq5cba

Please fix this as soon as possible.

**Comment by longsleep** [comment]
Please check if still an issue and reopen if so.
