### ISSUE TITLE
Iridium 48.1 bad signature

### ISSUE THREAD

**Issue by mytbk** [iridium-browser/tracker#62]
I've downloaded the source of Iridium 48.1, but the signature is bad.
BTW: Can you give some checksum files so that I can verify the files by hash?

[irudog@mytbk-laptop iridium]$ sha256sum iridium-browser-48.1.tar*
547de508d1c297dc5ec84162918580a7702e1ab95dfc991205bdd0cc0b444b1d  iridium-browser-48.1.tar
66c5feb729176c75a19ce195eb10a631790855ea67af985442c362e3775c41e7  iridium-browser-48.1.tar.asc
8f542ae1d3029c254c36dce5e540a6653700236be6808de6d3c29537e47a0725  iridium-browser-48.1.tar.xz
[irudog@mytbk-laptop iridium]$ gpg --verify iridium-browser-48.1.tar.asc
gpg: assuming signed data in 'iridium-browser-48.1.tar'
gpg: Signature made Mon Feb 15 16:25:03 2016 CST using RSA key ID 297DFB7D
gpg: BAD signature from "Jan Engelhardt jengelh@inai.de" [unknown]

**Comment by longsleep** [comment]
48.1 is obsolete - closing.
