### ISSUE TITLE
chrome://inspect does not work

### ISSUE THREAD

**Issue by whirish** [iridium-browser/tracker#76]
I'm running the latest Iridium on Debian 8.4 and when I navigate to about:inspect or chrome://inspect, I can see the list of devices with USB debugging enabled, as expected. However, clicking inspect next to any of these devices results in a blank pop-up window. 
Note that this does work as expected in the latest Chromium, however.

**Comment by souldanger** [comment]
This issue has been solved in the latest release!
Please download from [https://iridiumbrowser.de/downloads/](https://iridiumbrowser.de/downloads/ "download Iridium Browser")
