### ISSUE TITLE
Use different proxy to system

### ISSUE THREAD

**Issue by patrickkelso** [iridium-browser/tracker#87]
I know Google has no interest in fixing this in Chrome/Chromium, but for real privacy I'd like to be able to specify a different proxy configuration for Iridium from the system proxies. Is this something Iridium could do? The one thing that keeps me coming back to Firefox is the ability to use different proxies

**Comment by donestefan** [comment]
There are addons like "[foxyproxy](https://chrome.google.com/webstore/detail/foxyproxy-basic/dookpfaalaaappcdneeahomimbllocnb)" which already provide the functionality you ask for.

**Comment by patrickkelso** [comment]
Sure, but the privacy focused user may not like having plugins installed and that's a whole other set of developers I have to trust and source code I have to review. (Assuming I can)

There are many ways to solve this, I would have thought that in a privacy focused browser this would be built in.

**Comment by medozas** [comment]
sorry, this is nothing we're going to implement - the system proxy setting is quite bundled and we see no advantage in terms of privacy to not use the system defined proxy ... ?
