### ISSUE TITLE
Proprietary components?

### ISSUE THREAD

**Issue by davidhedlund** [iridium-browser/tracker#93]
I will approve the Free Software Directory entry http://directory.fsf.org/wiki/Iridium when the developers of Iridium can verify that it is entirely free software.

I've heard that the proprietary extension Ghostery is included. Is this true?

**Comment by davidhedlund** [comment]
[mylabel:non-free software candidate](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Anon-free software candidate%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by onpon4** [comment]
Ding! Just want to chime in and say I'm curious about the answer to this question too. Is there any chance someone from the project could clarify whether or not Iridium contains any proprietary components?

**Comment by souldanger** [comment]
Hi Julie
yes we can confirm Iridium Browser is fully Open-Source!
Thanks

**Comment by souldanger** [comment]
Hi Danyl,
fully Open-Source means 100% including any and all components, plugins, extensions, patches, snippets and everything else it is shipped with by default.
Also see [Wiki on GitHub](https://github.com/iridium-browser/tracker/wiki/Differences-between-Iridium-and-Chromium "Differences between Iridium and Chromium"){:target="_blank" rel="noreferrer"} for further information

**Comment by strypey** [comment]
Thanks so much for this prompt and  thorough response! I look forward to seeing the Iridium page appear in the FSD.

**Comment by davidhedlund** [comment]
@strypey @souldanger Iridium is still under [investigation](https://directory.fsf.org/wiki/Free_Software_Directory:Free_software_evaluation) since it's using the code base of [Chromium](https://lists.gnu.org/archive/html/directory-discuss/2017-12/msg00008.html).

**Comment by strypey** [comment]
Thanks for the update @davidhedlund . Could we perhaps discuss what this investigation involves on the [Trisquel forum thread about this](https://trisquel.info/en/forum/confirmation-iridium-libre), and return to this thread when we have new information, questions, or requests for the Iridium team?

**Comment by davidhedlund** [comment]
@strypey I think we should identify the Electron issue in [https://bugs.chromium.org/p/chromium/issues/list Chromium] first of all. I could not find anything related to it in the link but feel free to submit at ticket and paste it here.

**Comment by strypey** [comment]
@souldanger are you able to comment on the issues raised about Chromium and Electron in these links?

**Comment by souldanger** [comment]
I can't, but have copied some of our devs

@fkr @medozas @jengelh @longsleep 
hi guys,
can you please reply to the issue

**Comment by jengelh** [comment]
>I've heard that the proprietary extension Ghostery is included. Is this true?

Is it?

I don't know all the crap that is being delivered with the original source tarball. Grep suggests there is no ghostery, and the lawyers at e.g. SUSE are also confident the OSI criteria is fulfilled.

**Comment by davidhedlund** [comment]
> I am Loïc, aka Magic Banana on Internet.  I write to you about the
> Iridium entry you added to the Free Software Directory.
> 
> Along an old conversation on the Trisquel GNU/Linux forum, I ended up
> taking a quick look at Chromium's code.  I easily found many problems,
> such as the presence of unrar, under a proprietary license, and of much
> minified JavaScript (hence, not source code), including Google
> Analytics:
> https://trisquel.info/forum/free-software-foundations-problems#comment-128239
> and the post below.
> 
> It looks like those same problems are present in Iridium's source:
> https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/third_party/unrar/LICENSE
> https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/third_party/analytics/google-analytics-bundle.js
> https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/chrome/test/data/chromeproxy/extension/google-analytics-bundle.js
> etc.

**Comment by dimqua** [comment]
The for the info!
